"""
RxBuddy Drug Catalog — v1
==========================

Maintains a curated list of ~200 target drugs (top US prescriptions + common OTCs)
with RxNorm CUI, brand/generic mappings, drug class, and DailyMed setID.

Usage
-----
  from drug_catalog import find_drug, preload_catalog, DrugRecord

  record = find_drug("Tylenol")       # → DrugRecord(canonical="acetaminophen", ...)
  record = find_drug("ibuprofin")     # → DrugRecord via RxNorm spell-correction
  preload_catalog()                   # call at startup to warm the cache

Data refresh
------------
  POST /admin/refresh-catalog → calls preload_catalog(force=True)
  The catalog RxCUI/setID entries are fetched lazily and cached in-process (lru_cache).

Data priority
-------------
  FDA label (OpenFDA/DailyMed) > RxNorm canonical > drug_catalog defaults
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import Optional

logger = logging.getLogger("rxbuddy.drug_catalog")


# ── DrugRecord ───────────────────────────────────────────────────────────────

@dataclass
class DrugRecord:
    canonical_name: str
    rxcui:          Optional[str]       = None
    brand_names:    list[str]           = field(default_factory=list)
    generic_names:  list[str]           = field(default_factory=list)
    drug_class:     str                 = "General"
    dailymed_setid: Optional[str]       = None
    nda_number:     Optional[str]       = None
    is_high_risk:   bool                = False  # narrow TI or known dangerous
    common_side_effects:  list[str]     = field(default_factory=list)
    serious_side_effects: list[str]     = field(default_factory=list)
    mechanism_simple:     str           = ""

    @property
    def all_names(self) -> list[str]:
        """All known names for this drug (canonical + brands + generics), lowercase."""
        return [self.canonical_name] + self.brand_names + self.generic_names

    def dailymed_url(self) -> Optional[str]:
        if self.dailymed_setid:
            return f"https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid={self.dailymed_setid}"
        return f"https://dailymed.nlm.nih.gov/dailymed/search.cfm?labeltype=all&query={self.canonical_name}"


# ── Seed data ─────────────────────────────────────────────────────────────────
# Tuple: (canonical, [brands], drug_class, high_risk, [common_se], [serious_se], mechanism)
# Source: CMS top-prescribed medications, ASHP, IMS Health, FDA Orange Book.

_SEED: list[tuple] = [
    # ── Analgesics / Anti-inflammatory ───────────────────────────────────────
    ("acetaminophen", ["Tylenol", "Panadol", "Paracetamol", "Mapap"], "Analgesic", False,
     ["nausea", "stomach pain", "headache", "rash"],
     ["liver damage with overdose", "severe allergic reaction"],
     "This drug blocks pain signals and reduces fever by acting on the brain."),
    ("ibuprofen", ["Advil", "Motrin", "Nurofen"], "NSAID", False,
     ["stomach upset", "heartburn", "dizziness", "headache"],
     ["stomach bleeding", "kidney problems", "increased heart attack risk"],
     "This drug reduces pain and inflammation by blocking prostaglandin production."),
    ("naproxen", ["Aleve", "Naprosyn", "Anaprox"], "NSAID", False,
     ["stomach upset", "heartburn", "dizziness", "drowsiness"],
     ["stomach bleeding", "kidney problems", "increased heart attack risk"],
     "This drug reduces pain and inflammation by blocking prostaglandin production for longer than ibuprofen."),
    ("aspirin", ["Bayer", "Ecotrin", "Bufferin"], "NSAID/Antiplatelet", False,
     ["stomach upset", "heartburn", "nausea", "easy bruising"],
     ["stomach bleeding", "hemorrhagic stroke", "Reye syndrome in children"],
     "This drug reduces pain and prevents blood clots by blocking prostaglandins and platelet clumping."),
    ("celecoxib", ["Celebrex"], "NSAID (COX-2)", False,
     ["stomach pain", "diarrhea", "headache", "dizziness"],
     ["heart attack risk", "stroke risk", "stomach bleeding"],
     "This drug reduces pain by selectively blocking COX-2 enzyme with less stomach irritation."),
    ("meloxicam", ["Mobic"], "NSAID", False,
     ["stomach upset", "diarrhea", "dizziness", "headache"],
     ["stomach bleeding", "kidney problems", "heart attack risk"],
     "This drug reduces pain and inflammation by blocking COX enzymes."),
    ("diclofenac", ["Voltaren", "Cambia", "Zipsor"], "NSAID", False,
     ["stomach pain", "nausea", "diarrhea", "headache"],
     ["stomach bleeding", "liver damage", "heart attack risk"],
     "This drug reduces pain and inflammation by blocking prostaglandin production."),
    ("indomethacin", ["Indocin", "Tivorbex"], "NSAID", False,
     ["headache", "dizziness", "stomach upset", "nausea"],
     ["stomach bleeding", "kidney problems", "severe headache"],
     "This drug is a strong anti-inflammatory that blocks prostaglandin production."),
    ("ketorolac", ["Toradol"], "NSAID", False,
     ["stomach pain", "nausea", "headache", "drowsiness"],
     ["stomach bleeding", "kidney failure", "serious allergic reaction"],
     "This drug provides strong short-term pain relief by blocking prostaglandins."),
    ("tramadol", ["Ultram", "ConZip"], "Opioid Analgesic", True,
     ["nausea", "dizziness", "constipation", "drowsiness", "headache"],
     ["seizures", "serotonin syndrome", "respiratory depression", "dependence"],
     "This drug blocks pain signals by acting on opioid receptors and serotonin pathways."),
    ("hydrocodone", ["Vicodin", "Norco", "Lortab"], "Opioid Analgesic", True,
     ["drowsiness", "constipation", "nausea", "dizziness", "lightheadedness"],
     ["respiratory depression", "dependence and addiction", "overdose risk"],
     "This drug blocks pain signals by binding to opioid receptors in the brain."),
    ("oxycodone", ["OxyContin", "Percocet", "Roxicodone"], "Opioid Analgesic", True,
     ["constipation", "nausea", "drowsiness", "dizziness", "vomiting"],
     ["respiratory depression", "addiction and dependence", "overdose risk"],
     "This drug blocks pain signals by binding to opioid receptors in the brain and spinal cord."),
    ("morphine", ["MS Contin", "Kadian", "MSIR"], "Opioid Analgesic", True,
     ["constipation", "nausea", "drowsiness", "dizziness", "sweating"],
     ["respiratory depression", "severe low blood pressure", "addiction"],
     "This drug blocks pain signals by strongly binding to opioid receptors in the nervous system."),
    ("fentanyl", ["Duragesic", "Sublimaze", "Actiq"], "Opioid Analgesic", True,
     ["nausea", "constipation", "drowsiness", "dizziness", "sweating"],
     ["fatal respiratory depression", "overdose risk", "severe addiction"],
     "This drug is an extremely potent opioid that blocks pain signals at very low doses."),
    ("codeine", ["Tylenol with Codeine"], "Opioid Analgesic", True,
     ["constipation", "nausea", "drowsiness", "dizziness"],
     ["respiratory depression", "dependence", "life-threatening in ultra-rapid metabolizers"],
     "This drug is a mild opioid that the body converts to morphine to relieve pain."),
    ("buprenorphine", ["Suboxone", "Subutex", "Buprenex"], "Opioid Partial Agonist", True,
     ["headache", "nausea", "constipation", "insomnia", "sweating"],
     ["respiratory depression", "liver problems", "withdrawal if used with full opioids"],
     "This drug partially activates opioid receptors to treat pain and opioid addiction with lower overdose risk."),
    ("naloxone", ["Narcan", "Evzio"], "Opioid Antagonist", False,
     ["nausea", "vomiting", "sweating", "rapid heartbeat"],
     ["severe opioid withdrawal symptoms", "pulmonary edema"],
     "This drug reverses opioid overdoses by blocking opioid receptors."),
    ("methadone", ["Dolophine", "Methadose"], "Opioid", True,
     ["constipation", "drowsiness", "sweating", "nausea", "dizziness"],
     ["fatal heart rhythm changes (QT prolongation)", "respiratory depression", "addiction"],
     "This drug is a long-acting opioid used for severe pain and opioid addiction treatment."),

    # ── Cardiovascular ───────────────────────────────────────────────────────
    ("atorvastatin", ["Lipitor"], "Statin", False,
     ["muscle pain", "diarrhea", "upset stomach", "joint pain"],
     ["rhabdomyolysis (severe muscle breakdown)", "liver damage"],
     "This drug lowers cholesterol by blocking an enzyme the liver uses to make it."),
    ("rosuvastatin", ["Crestor", "Ezallor"], "Statin", False,
     ["headache", "muscle pain", "nausea", "weakness"],
     ["rhabdomyolysis", "liver damage", "kidney problems"],
     "This drug lowers cholesterol by blocking HMG-CoA reductase in the liver."),
    ("simvastatin", ["Zocor"], "Statin", False,
     ["muscle pain", "constipation", "nausea", "headache"],
     ["rhabdomyolysis", "liver damage"],
     "This drug lowers cholesterol by blocking the liver enzyme that produces it."),
    ("pravastatin", ["Pravachol"], "Statin", False,
     ["nausea", "headache", "dizziness", "muscle pain"],
     ["rhabdomyolysis", "liver damage"],
     "This drug lowers cholesterol by inhibiting cholesterol production in the liver."),
    ("lovastatin", ["Mevacor", "Altoprev"], "Statin", False,
     ["muscle pain", "constipation", "stomach upset", "headache"],
     ["rhabdomyolysis", "liver damage"],
     "This drug lowers cholesterol by blocking the liver enzyme HMG-CoA reductase."),
    ("pitavastatin", ["Livalo"], "Statin", False,
     ["muscle pain", "back pain", "diarrhea", "constipation"],
     ["rhabdomyolysis", "liver damage"],
     "This drug lowers cholesterol by blocking cholesterol production with fewer drug interactions."),
    ("ezetimibe", ["Zetia", "Ezetrol"], "Lipid-Lowering", False,
     ["diarrhea", "joint pain", "fatigue", "stomach pain"],
     ["liver problems", "muscle damage when combined with statins"],
     "This drug lowers cholesterol by blocking its absorption in the small intestine."),
    ("fenofibrate", ["TriCor", "Fenoglide", "Tricor"], "Fibrate", False,
     ["nausea", "stomach pain", "headache", "back pain"],
     ["liver damage", "gallstones", "rhabdomyolysis"],
     "This drug lowers triglycerides and raises good cholesterol by activating PPAR-alpha receptors."),
    ("lisinopril", ["Zestril", "Prinivil"], "ACE Inhibitor", False,
     ["dry cough", "dizziness", "headache", "fatigue"],
     ["angioedema (face swelling)", "kidney problems", "high potassium"],
     "This drug lowers blood pressure by blocking the enzyme that tightens blood vessels."),
    ("enalapril", ["Vasotec"], "ACE Inhibitor", False,
     ["dry cough", "dizziness", "headache", "fatigue"],
     ["angioedema", "kidney problems", "high potassium"],
     "This drug lowers blood pressure by blocking angiotensin-converting enzyme."),
    ("ramipril", ["Altace"], "ACE Inhibitor", False,
     ["dry cough", "dizziness", "fatigue", "headache"],
     ["angioedema", "kidney failure", "high potassium"],
     "This drug lowers blood pressure and protects the heart by blocking ACE."),
    ("benazepril", ["Lotensin"], "ACE Inhibitor", False,
     ["dry cough", "dizziness", "headache", "drowsiness"],
     ["angioedema", "kidney problems", "high potassium"],
     "This drug lowers blood pressure by blocking the enzyme that narrows blood vessels."),
    ("captopril", ["Capoten"], "ACE Inhibitor", False,
     ["dry cough", "dizziness", "loss of taste", "rash"],
     ["angioedema", "kidney problems", "low white blood cell count"],
     "This drug was the first ACE inhibitor used to lower blood pressure by relaxing blood vessels."),
    ("losartan", ["Cozaar"], "ARB", False,
     ["dizziness", "fatigue", "nasal congestion", "back pain"],
     ["kidney problems", "high potassium", "liver damage"],
     "This drug lowers blood pressure by blocking angiotensin II receptors without causing cough."),
    ("valsartan", ["Diovan"], "ARB", False,
     ["dizziness", "headache", "fatigue", "stomach pain"],
     ["kidney problems", "high potassium", "low blood pressure"],
     "This drug lowers blood pressure by blocking angiotensin II receptors on blood vessels."),
    ("olmesartan", ["Benicar"], "ARB", False,
     ["dizziness", "diarrhea", "back pain", "joint pain"],
     ["kidney problems", "severe chronic diarrhea (sprue-like enteropathy)"],
     "This drug lowers blood pressure by blocking angiotensin II receptors."),
    ("irbesartan", ["Avapro"], "ARB", False,
     ["dizziness", "fatigue", "diarrhea", "heartburn"],
     ["kidney problems", "high potassium"],
     "This drug lowers blood pressure and protects kidneys by blocking angiotensin II."),
    ("candesartan", ["Atacand"], "ARB", False,
     ["dizziness", "back pain", "sore throat", "fatigue"],
     ["kidney problems", "high potassium", "low blood pressure"],
     "This drug lowers blood pressure by blocking angiotensin II receptors on blood vessels."),
    ("telmisartan", ["Micardis"], "ARB", False,
     ["dizziness", "back pain", "diarrhea", "sinus pain"],
     ["kidney problems", "high potassium"],
     "This drug lowers blood pressure by blocking angiotensin II receptors with a long duration of action."),
    ("amlodipine", ["Norvasc"], "Calcium Channel Blocker", False,
     ["swelling of ankles", "dizziness", "flushing", "fatigue"],
     ["severe low blood pressure", "worsening chest pain"],
     "This drug lowers blood pressure by relaxing blood vessel walls through calcium channel blockade."),
    ("nifedipine", ["Procardia", "Adalat"], "Calcium Channel Blocker", False,
     ["headache", "flushing", "dizziness", "swelling of ankles"],
     ["severe low blood pressure", "rapid heartbeat"],
     "This drug lowers blood pressure by blocking calcium channels in blood vessel walls."),
    ("diltiazem", ["Cardizem", "Tiazac", "Cartia XT"], "Calcium Channel Blocker", False,
     ["dizziness", "headache", "swelling", "slow heartbeat", "flushing"],
     ["severe bradycardia", "heart block", "heart failure worsening"],
     "This drug lowers blood pressure and slows the heart by blocking calcium channels."),
    ("verapamil", ["Calan", "Isoptin", "Verelan"], "Calcium Channel Blocker", True,
     ["constipation", "dizziness", "headache", "low blood pressure", "fatigue"],
     ["severe bradycardia", "heart block", "heart failure"],
     "This drug lowers blood pressure and heart rate by blocking calcium channels in the heart."),
    ("metoprolol", ["Lopressor", "Toprol XL"], "Beta Blocker", False,
     ["fatigue", "dizziness", "slow heart rate", "cold hands and feet"],
     ["severe bradycardia", "heart block", "bronchospasm in asthma patients"],
     "This drug slows the heart rate by blocking adrenaline receptors in the heart."),
    ("atenolol", ["Tenormin"], "Beta Blocker", False,
     ["fatigue", "cold hands", "dizziness", "slow heartbeat"],
     ["severe bradycardia", "heart block", "bronchospasm"],
     "This drug slows the heart and lowers blood pressure by blocking beta-1 receptors."),
    ("carvedilol", ["Coreg"], "Beta Blocker", False,
     ["dizziness", "fatigue", "low blood pressure", "diarrhea", "weight gain"],
     ["severe bradycardia", "worsening heart failure initially", "liver damage"],
     "This drug blocks both alpha and beta receptors to lower blood pressure and protect the heart."),
    ("propranolol", ["Inderal", "InnoPran XL"], "Beta Blocker", False,
     ["fatigue", "cold hands", "dizziness", "nausea", "slow heartbeat"],
     ["severe bradycardia", "bronchospasm", "depression"],
     "This drug blocks adrenaline receptors throughout the body to slow the heart and reduce anxiety."),
    ("bisoprolol", ["Zebeta"], "Beta Blocker", False,
     ["fatigue", "dizziness", "diarrhea", "slow heartbeat"],
     ["severe bradycardia", "heart block"],
     "This drug selectively blocks beta-1 receptors to slow the heart and lower blood pressure."),
    ("nebivolol", ["Bystolic"], "Beta Blocker", False,
     ["headache", "fatigue", "dizziness", "diarrhea"],
     ["severe bradycardia", "heart block"],
     "This drug lowers blood pressure by blocking beta receptors and releasing nitric oxide to relax vessels."),
    ("hydrochlorothiazide", ["Microzide", "HydroDIURIL"], "Thiazide Diuretic", False,
     ["frequent urination", "dizziness", "low potassium", "increased blood sugar"],
     ["severe electrolyte imbalance", "gout flare", "severe allergic reaction"],
     "This drug lowers blood pressure by helping the kidneys remove extra salt and water."),
    ("chlorthalidone", ["Hygroton", "Thalitone"], "Thiazide Diuretic", False,
     ["frequent urination", "dizziness", "low potassium", "increased blood sugar"],
     ["severe electrolyte imbalance", "gout flare"],
     "This drug is a long-acting diuretic that helps the kidneys remove salt and water to lower blood pressure."),
    ("furosemide", ["Lasix"], "Loop Diuretic", False,
     ["frequent urination", "dizziness", "low potassium", "dehydration"],
     ["severe electrolyte imbalance", "hearing loss", "kidney damage"],
     "This drug powerfully removes excess fluid by blocking salt reabsorption in the kidneys."),
    ("torsemide", ["Demadex"], "Loop Diuretic", False,
     ["frequent urination", "dizziness", "headache", "low potassium"],
     ["severe electrolyte imbalance", "hearing loss"],
     "This drug removes excess fluid by blocking salt reabsorption in the loop of Henle."),
    ("bumetanide", ["Bumex"], "Loop Diuretic", False,
     ["frequent urination", "dizziness", "muscle cramps", "low potassium"],
     ["severe electrolyte imbalance", "hearing loss"],
     "This drug is a potent loop diuretic that removes excess fluid from the body."),
    ("spironolactone", ["Aldactone", "CaroSpir"], "Potassium-Sparing Diuretic", False,
     ["breast tenderness", "dizziness", "nausea", "menstrual irregularities"],
     ["dangerously high potassium", "kidney problems"],
     "This drug blocks aldosterone to remove fluid while keeping potassium levels stable."),
    ("eplerenone", ["Inspra"], "Potassium-Sparing Diuretic", False,
     ["dizziness", "diarrhea", "fatigue", "flu-like symptoms"],
     ["dangerously high potassium", "kidney problems"],
     "This drug selectively blocks aldosterone to protect the heart and remove excess fluid."),
    ("digoxin", ["Lanoxin"], "Cardiac Glycoside", True,
     ["nausea", "vomiting", "loss of appetite", "visual disturbances (yellow vision)"],
     ["fatal heart rhythm changes", "digoxin toxicity"],
     "This drug strengthens heart contractions and slows heart rate by inhibiting sodium-potassium pump."),
    ("warfarin", ["Coumadin", "Jantoven"], "Anticoagulant", True,
     ["easy bruising", "bleeding gums", "prolonged bleeding from cuts"],
     ["serious internal bleeding", "hemorrhagic stroke", "skin necrosis"],
     "This drug prevents blood clots by blocking vitamin K-dependent clotting factors."),
    ("apixaban", ["Eliquis"], "Anticoagulant (DOAC)", True,
     ["easy bruising", "minor bleeding", "nausea"],
     ["serious bleeding", "spinal blood clots with epidurals"],
     "This drug prevents blood clots by directly blocking factor Xa in the clotting cascade."),
    ("rivaroxaban", ["Xarelto"], "Anticoagulant (DOAC)", True,
     ["easy bruising", "minor bleeding", "back pain"],
     ["serious bleeding", "spinal blood clots with epidurals"],
     "This drug prevents blood clots by directly inhibiting factor Xa."),
    ("dabigatran", ["Pradaxa"], "Anticoagulant (DOAC)", True,
     ["stomach pain", "heartburn", "nausea", "easy bruising"],
     ["serious bleeding", "spinal blood clots"],
     "This drug prevents blood clots by directly blocking thrombin."),
    ("edoxaban", ["Savaysa"], "Anticoagulant (DOAC)", True,
     ["easy bruising", "minor bleeding", "rash"],
     ["serious bleeding", "spinal blood clots"],
     "This drug prevents blood clots by directly blocking factor Xa."),
    ("heparin", ["Heparin Sodium"], "Anticoagulant", True,
     ["easy bruising", "pain at injection site", "mild bleeding"],
     ["serious bleeding", "heparin-induced thrombocytopenia (HIT)", "osteoporosis with long use"],
     "This drug prevents blood clots by activating antithrombin III to block clotting factors."),
    ("enoxaparin", ["Lovenox", "Clexane"], "Anticoagulant (LMWH)", True,
     ["injection site bruising", "mild bleeding", "nausea"],
     ["serious bleeding", "heparin-induced thrombocytopenia", "spinal blood clots"],
     "This drug prevents blood clots by blocking factor Xa more selectively than regular heparin."),
    ("clopidogrel", ["Plavix"], "Antiplatelet", True,
     ["easy bruising", "stomach pain", "diarrhea", "itching"],
     ["serious bleeding", "thrombotic thrombocytopenic purpura (TTP)"],
     "This drug prevents blood clots by blocking a receptor on platelets."),
    ("prasugrel", ["Effient"], "Antiplatelet", True,
     ["easy bruising", "bleeding", "headache", "back pain"],
     ["life-threatening bleeding", "thrombotic thrombocytopenic purpura"],
     "This drug prevents blood clots by irreversibly blocking P2Y12 receptors on platelets."),
    ("ticagrelor", ["Brilinta"], "Antiplatelet", True,
     ["shortness of breath", "easy bruising", "headache", "nausea"],
     ["serious bleeding", "slow heartbeat"],
     "This drug prevents blood clots by reversibly blocking P2Y12 receptors on platelets."),
    ("amiodarone", ["Pacerone", "Cordarone"], "Antiarrhythmic", True,
     ["nausea", "fatigue", "tremor", "skin sensitivity to sun"],
     ["lung toxicity", "thyroid problems", "liver damage", "vision damage"],
     "This drug controls heart rhythm by blocking multiple ion channels in the heart."),
    ("sotalol", ["Betapace", "Sorine"], "Antiarrhythmic", True,
     ["fatigue", "dizziness", "slow heartbeat", "nausea"],
     ["dangerous heart rhythm changes (torsades de pointes)", "worsening heart failure"],
     "This drug controls heart rhythm by blocking both beta receptors and potassium channels."),
    ("flecainide", ["Tambocor"], "Antiarrhythmic", True,
     ["dizziness", "blurred vision", "headache", "nausea"],
     ["new or worsened arrhythmias", "heart failure"],
     "This drug controls heart rhythm by blocking sodium channels in the heart."),
    ("dronedarone", ["Multaq"], "Antiarrhythmic", True,
     ["diarrhea", "nausea", "stomach pain", "fatigue"],
     ["worsening heart failure", "liver damage", "lung damage"],
     "This drug controls heart rhythm similarly to amiodarone but with fewer thyroid and lung side effects."),
    ("sacubitril", ["Entresto"], "ARNi", False,
     ["low blood pressure", "dizziness", "cough", "high potassium"],
     ["angioedema", "kidney failure"],
     "This drug treats heart failure by blocking both neprilysin and angiotensin receptors."),
    ("hydralazine", ["Apresoline"], "Vasodilator", False,
     ["headache", "rapid heartbeat", "flushing", "nausea"],
     ["drug-induced lupus", "severe low blood pressure"],
     "This drug lowers blood pressure by directly relaxing the muscles in blood vessel walls."),
    ("isosorbide mononitrate", ["Imdur", "ISMO"], "Nitrate", False,
     ["headache", "dizziness", "flushing", "lightheadedness"],
     ["severe low blood pressure", "fainting"],
     "This drug prevents chest pain by releasing nitric oxide to widen blood vessels."),
    ("nitroglycerin", ["Nitrostat", "Nitrolingual", "NitroMist"], "Nitrate", False,
     ["headache", "dizziness", "flushing", "lightheadedness"],
     ["severe low blood pressure", "fainting"],
     "This drug quickly relieves chest pain by releasing nitric oxide to widen coronary arteries."),
    ("ivabradine", ["Corlanor"], "Funny Channel Inhibitor", False,
     ["slow heartbeat", "visual disturbances (phosphenes)", "dizziness"],
     ["severe bradycardia", "atrial fibrillation"],
     "This drug slows the heart rate by blocking the funny channel in the heart's pacemaker cells."),

    # ── Diabetes ─────────────────────────────────────────────────────────────
    ("metformin", ["Glucophage", "Fortamet", "Riomet"], "Biguanide", False,
     ["nausea", "diarrhea", "stomach upset", "loss of appetite"],
     ["lactic acidosis (rare but serious)", "vitamin B12 deficiency"],
     "This drug lowers blood sugar by reducing glucose production in the liver."),
    ("glipizide", ["Glucotrol"], "Sulfonylurea", False,
     ["low blood sugar", "weight gain", "nausea", "dizziness"],
     ["severe hypoglycemia", "blood cell count changes"],
     "This drug lowers blood sugar by stimulating the pancreas to release more insulin."),
    ("glimepiride", ["Amaryl"], "Sulfonylurea", False,
     ["low blood sugar", "weight gain", "dizziness", "nausea"],
     ["severe hypoglycemia", "blood disorders"],
     "This drug stimulates insulin release from the pancreas to lower blood sugar."),
    ("glyburide", ["DiaBeta", "Micronase", "Glynase"], "Sulfonylurea", False,
     ["low blood sugar", "weight gain", "nausea", "heartburn"],
     ["severe hypoglycemia", "liver problems"],
     "This drug forces the pancreas to release more insulin to lower blood sugar."),
    ("pioglitazone", ["Actos"], "Thiazolidinedione", False,
     ["weight gain", "swelling", "headache", "muscle pain"],
     ["heart failure", "bladder cancer risk", "bone fractures"],
     "This drug makes the body's cells more sensitive to insulin."),
    ("sitagliptin", ["Januvia"], "DPP-4 Inhibitor", False,
     ["upper respiratory infection", "headache", "stomach pain"],
     ["pancreatitis", "severe joint pain"],
     "This drug lowers blood sugar by blocking the enzyme that breaks down incretin hormones."),
    ("saxagliptin", ["Onglyza"], "DPP-4 Inhibitor", False,
     ["upper respiratory infection", "headache", "urinary tract infection"],
     ["pancreatitis", "heart failure risk"],
     "This drug lowers blood sugar by preserving incretin hormones that stimulate insulin."),
    ("linagliptin", ["Tradjenta"], "DPP-4 Inhibitor", False,
     ["runny nose", "sore throat", "cough"],
     ["pancreatitis", "severe joint pain"],
     "This drug lowers blood sugar by blocking DPP-4 enzyme without needing kidney dose adjustment."),
    ("alogliptin", ["Nesina"], "DPP-4 Inhibitor", False,
     ["upper respiratory infection", "headache", "runny nose"],
     ["pancreatitis", "heart failure risk", "liver problems"],
     "This drug lowers blood sugar by inhibiting DPP-4 to preserve incretin hormones."),
    ("empagliflozin", ["Jardiance"], "SGLT-2 Inhibitor", False,
     ["urinary tract infections", "yeast infections", "frequent urination", "thirst"],
     ["diabetic ketoacidosis", "kidney problems", "genital gangrene (rare)"],
     "This drug lowers blood sugar by making the kidneys remove more glucose through urine."),
    ("dapagliflozin", ["Farxiga"], "SGLT-2 Inhibitor", False,
     ["urinary tract infections", "yeast infections", "frequent urination", "back pain"],
     ["diabetic ketoacidosis", "kidney problems", "dehydration"],
     "This drug lowers blood sugar and protects the heart by causing glucose loss through urine."),
    ("canagliflozin", ["Invokana"], "SGLT-2 Inhibitor", False,
     ["yeast infections", "urinary tract infections", "frequent urination"],
     ["diabetic ketoacidosis", "toe amputation risk", "bone fractures"],
     "This drug lowers blood sugar by blocking glucose reabsorption in the kidneys."),
    ("ertugliflozin", ["Steglatro"], "SGLT-2 Inhibitor", False,
     ["yeast infections", "urinary tract infections", "frequent urination"],
     ["diabetic ketoacidosis", "kidney problems"],
     "This drug lowers blood sugar by preventing the kidneys from reabsorbing glucose."),
    ("liraglutide", ["Victoza", "Saxenda"], "GLP-1 Agonist", False,
     ["nausea", "vomiting", "diarrhea", "constipation", "stomach pain"],
     ["pancreatitis", "thyroid tumors (in animals)", "gallbladder problems"],
     "This drug lowers blood sugar and reduces appetite by mimicking the GLP-1 hormone."),
    ("semaglutide", ["Ozempic", "Wegovy", "Rybelsus"], "GLP-1 Agonist", False,
     ["nausea", "vomiting", "diarrhea", "constipation", "stomach pain"],
     ["pancreatitis", "thyroid tumors (in animals)", "gallbladder problems"],
     "This drug mimics GLP-1 hormone to lower blood sugar, reduce appetite, and promote weight loss."),
    ("dulaglutide", ["Trulicity"], "GLP-1 Agonist", False,
     ["nausea", "diarrhea", "vomiting", "stomach pain", "decreased appetite"],
     ["pancreatitis", "thyroid tumors (in animals)"],
     "This drug mimics GLP-1 hormone to lower blood sugar with weekly dosing."),
    ("exenatide", ["Byetta", "Bydureon"], "GLP-1 Agonist", False,
     ["nausea", "vomiting", "diarrhea", "dizziness", "headache"],
     ["pancreatitis", "kidney problems"],
     "This drug mimics GLP-1 hormone to stimulate insulin release and slow digestion."),
    ("tirzepatide", ["Mounjaro", "Zepbound"], "GIP/GLP-1 Agonist", False,
     ["nausea", "diarrhea", "vomiting", "constipation", "stomach pain"],
     ["pancreatitis", "thyroid tumors (in animals)", "gallbladder problems"],
     "This drug activates both GIP and GLP-1 receptors for powerful blood sugar and weight control."),
    ("insulin glargine", ["Lantus", "Basaglar", "Toujeo"], "Insulin", True,
     ["low blood sugar", "weight gain", "injection site reactions", "swelling"],
     ["severe hypoglycemia", "allergic reaction"],
     "This drug provides steady background insulin for 24 hours to control blood sugar."),
    ("insulin detemir", ["Levemir"], "Insulin", True,
     ["low blood sugar", "weight gain", "injection site reactions"],
     ["severe hypoglycemia", "allergic reaction"],
     "This drug provides long-acting background insulin by binding to proteins in the blood."),
    ("insulin degludec", ["Tresiba"], "Insulin", True,
     ["low blood sugar", "weight gain", "injection site reactions"],
     ["severe hypoglycemia", "allergic reaction"],
     "This drug provides ultra-long-acting insulin lasting over 42 hours."),
    ("insulin aspart", ["NovoLog", "Fiasp"], "Insulin", True,
     ["low blood sugar", "injection site reactions", "weight gain"],
     ["severe hypoglycemia", "allergic reaction"],
     "This drug is a rapid-acting insulin that starts working within minutes of injection."),
    ("insulin lispro", ["Humalog", "Admelog"], "Insulin", True,
     ["low blood sugar", "injection site reactions", "weight gain"],
     ["severe hypoglycemia", "allergic reaction"],
     "This drug is a rapid-acting insulin used to cover blood sugar spikes at meals."),
    ("insulin regular", ["Humulin R", "Novolin R"], "Insulin", True,
     ["low blood sugar", "weight gain", "injection site reactions"],
     ["severe hypoglycemia", "allergic reaction"],
     "This drug is a short-acting insulin that mimics the body's natural mealtime insulin release."),
    ("acarbose", ["Precose"], "Alpha-Glucosidase Inhibitor", False,
     ["gas", "bloating", "diarrhea", "stomach pain"],
     ["liver problems", "intestinal obstruction"],
     "This drug slows digestion of carbohydrates to prevent blood sugar spikes after meals."),
    ("repaglinide", ["Prandin"], "Meglitinide", False,
     ["low blood sugar", "headache", "upper respiratory infection"],
     ["severe hypoglycemia", "liver problems"],
     "This drug stimulates rapid short-term insulin release from the pancreas at mealtimes."),

    # ── Respiratory ──────────────────────────────────────────────────────────
    ("albuterol", ["ProAir", "Ventolin", "Proventil", "AccuNeb"], "SABA", False,
     ["tremor", "nervousness", "rapid heartbeat", "headache"],
     ["severe allergic reaction", "paradoxical bronchospasm"],
     "This drug relaxes airway muscles quickly to relieve asthma and breathing difficulty."),
    ("levalbuterol", ["Xopenex"], "SABA", False,
     ["tremor", "nervousness", "headache", "rapid heartbeat"],
     ["paradoxical bronchospasm", "chest pain"],
     "This drug is a purified form of albuterol that relaxes airway muscles with fewer heart side effects."),
    ("salmeterol", ["Serevent"], "LABA", False,
     ["headache", "sore throat", "nasal congestion", "cough"],
     ["asthma-related death if used alone", "paradoxical bronchospasm"],
     "This drug relaxes airway muscles for 12 hours to prevent asthma attacks."),
    ("formoterol", ["Foradil", "Perforomist"], "LABA", False,
     ["tremor", "headache", "palpitations", "sore throat"],
     ["asthma-related death if used alone", "paradoxical bronchospasm"],
     "This drug is a fast-onset long-acting bronchodilator that keeps airways open for 12 hours."),
    ("tiotropium", ["Spiriva"], "LAMA", False,
     ["dry mouth", "constipation", "urinary retention", "blurred vision"],
     ["severe allergic reaction", "worsening glaucoma"],
     "This drug keeps airways open for 24 hours by blocking acetylcholine receptors in the lungs."),
    ("umeclidinium", ["Incruse Ellipta"], "LAMA", False,
     ["runny nose", "cough", "joint pain", "sore throat"],
     ["paradoxical bronchospasm", "worsening urinary retention"],
     "This drug is a long-acting anticholinergic that relaxes airways for 24 hours."),
    ("ipratropium", ["Atrovent"], "Anticholinergic Bronchodilator", False,
     ["dry mouth", "cough", "headache", "nausea"],
     ["paradoxical bronchospasm", "worsening glaucoma"],
     "This drug opens airways by blocking acetylcholine receptors in the lungs."),
    ("fluticasone", ["Flovent", "Flonase", "Arnuity"], "ICS", False,
     ["sore throat", "hoarseness", "oral thrush", "headache", "nosebleed"],
     ["adrenal suppression with high doses", "bone density loss", "growth delay in children"],
     "This drug reduces airway inflammation by mimicking cortisol to suppress immune responses in the lungs."),
    ("budesonide", ["Pulmicort", "Rhinocort", "Entocort"], "ICS", False,
     ["sore throat", "headache", "nausea", "oral thrush"],
     ["adrenal suppression", "bone density loss"],
     "This drug reduces inflammation in the airways or gut by acting locally as a corticosteroid."),
    ("beclomethasone", ["QVAR", "Beconase"], "ICS", False,
     ["sore throat", "hoarseness", "oral thrush", "cough"],
     ["adrenal suppression", "bone density loss"],
     "This drug reduces airway inflammation as an inhaled corticosteroid."),
    ("mometasone", ["Nasonex", "Asmanex"], "ICS", False,
     ["headache", "sore throat", "nosebleed", "oral thrush"],
     ["adrenal suppression", "bone density loss"],
     "This drug reduces nasal or lung inflammation as a corticosteroid spray or inhaler."),
    ("ciclesonide", ["Alvesco", "Omnaris"], "ICS", False,
     ["headache", "nosebleed", "ear pain", "cough"],
     ["adrenal suppression", "bone density loss"],
     "This drug is a prodrug corticosteroid that activates in the lungs for targeted anti-inflammatory action."),
    ("montelukast", ["Singulair"], "Leukotriene Antagonist", False,
     ["headache", "stomach pain", "fatigue", "upper respiratory infection"],
     ["neuropsychiatric effects (mood changes, suicidal thoughts)", "liver problems"],
     "This drug blocks leukotrienes to reduce inflammation and mucus in the airways."),
    ("roflumilast", ["Daliresp"], "PDE-4 Inhibitor", False,
     ["diarrhea", "nausea", "headache", "weight loss"],
     ["psychiatric symptoms (depression, suicidal thoughts)", "weight loss"],
     "This drug reduces lung inflammation by blocking the PDE-4 enzyme."),
    ("theophylline", ["Theo-Dur", "Uniphyl", "Theo-24"], "Bronchodilator", True,
     ["nausea", "headache", "insomnia", "rapid heartbeat", "tremor"],
     ["seizures at high levels", "fatal heart arrhythmias"],
     "This drug opens airways and reduces inflammation by blocking phosphodiesterase and adenosine receptors."),
    ("prednisone", ["Deltasone", "Rayos"], "Corticosteroid", False,
     ["weight gain", "mood changes", "insomnia", "increased appetite", "acne"],
     ["osteoporosis", "diabetes", "adrenal suppression", "severe infections"],
     "This drug suppresses the immune system and reduces inflammation by mimicking cortisol."),
    ("methylprednisolone", ["Medrol", "Depo-Medrol", "Solu-Medrol"], "Corticosteroid", False,
     ["nausea", "headache", "dizziness", "insomnia", "increased appetite"],
     ["osteoporosis", "adrenal suppression", "severe infections"],
     "This drug is a synthetic corticosteroid that powerfully reduces inflammation."),
    ("dexamethasone", ["Decadron", "Dexamethasone Intensol"], "Corticosteroid", False,
     ["insomnia", "increased appetite", "mood changes", "flushing"],
     ["osteoporosis", "adrenal suppression", "hyperglycemia"],
     "This drug is a long-acting potent corticosteroid used to reduce severe inflammation."),
    ("triamcinolone", ["Kenalog", "Nasacort", "Trivaris"], "Corticosteroid", False,
     ["injection site pain", "skin thinning", "headache", "nausea"],
     ["adrenal suppression", "osteoporosis"],
     "This drug reduces inflammation as an injectable or topical corticosteroid."),
    ("cetirizine", ["Zyrtec", "Reactine"], "Antihistamine (2nd gen)", False,
     ["drowsiness", "dry mouth", "fatigue", "headache"],
     ["severe allergic reaction"],
     "This drug blocks histamine receptors to relieve allergy symptoms with less sedation than older antihistamines."),
    ("loratadine", ["Claritin", "Alavert"], "Antihistamine (2nd gen)", False,
     ["headache", "dry mouth", "fatigue", "drowsiness"],
     ["severe allergic reaction"],
     "This drug blocks histamine to relieve allergy symptoms without significant drowsiness."),
    ("fexofenadine", ["Allegra"], "Antihistamine (2nd gen)", False,
     ["headache", "nausea", "dizziness"],
     ["severe allergic reaction"],
     "This drug blocks histamine receptors to treat allergies without crossing into the brain to cause drowsiness."),
    ("desloratadine", ["Clarinex"], "Antihistamine (2nd gen)", False,
     ["sore throat", "dry mouth", "fatigue", "headache"],
     ["severe allergic reaction"],
     "This drug is an active metabolite of loratadine that blocks histamine with minimal sedation."),
    ("levocetirizine", ["Xyzal"], "Antihistamine (2nd gen)", False,
     ["drowsiness", "dry mouth", "fatigue", "sore throat"],
     ["severe allergic reaction"],
     "This drug is the active form of cetirizine that blocks histamine receptors more potently."),
    ("diphenhydramine", ["Benadryl", "ZzzQuil", "Unisom"], "Antihistamine (1st gen)", False,
     ["drowsiness", "dry mouth", "dizziness", "constipation", "blurred vision"],
     ["seizures with overdose", "urinary retention"],
     "This drug blocks histamine and crosses into the brain, causing sedation along with allergy relief."),
    ("pseudoephedrine", ["Sudafed"], "Decongestant", False,
     ["trouble sleeping", "nervousness", "dizziness", "fast heartbeat", "headache"],
     ["severe high blood pressure", "stroke"],
     "This drug shrinks blood vessels in the nasal passages to relieve congestion."),
    ("guaifenesin", ["Mucinex", "Robitussin"], "Expectorant", False,
     ["nausea", "vomiting", "dizziness", "headache"],
     ["kidney stones with very high doses"],
     "This drug thins mucus in the airways to make coughs more productive."),
    ("dextromethorphan", ["Robitussin DM", "Delsym", "NyQuil"], "Antitussive", False,
     ["dizziness", "drowsiness", "nausea", "stomach upset"],
     ["serotonin syndrome with other drugs", "abuse potential"],
     "This drug suppresses cough by acting on the cough center in the brain."),
    ("benralizumab", ["Fasenra"], "Biologic (Anti-IL-5Ra)", False,
     ["headache", "sore throat", "injection site reactions"],
     ["anaphylaxis", "parasitic infection worsening"],
     "This drug treats severe eosinophilic asthma by destroying eosinophils through anti-IL-5 receptor antibody action."),
    ("mepolizumab", ["Nucala"], "Biologic (Anti-IL-5)", False,
     ["headache", "injection site reactions", "back pain", "fatigue"],
     ["anaphylaxis", "herpes zoster reactivation"],
     "This drug treats severe eosinophilic asthma by blocking interleukin-5."),
    ("dupilumab", ["Dupixent"], "Biologic (Anti-IL-4/13)", False,
     ["injection site reactions", "eye inflammation", "cold sores"],
     ["anaphylaxis", "joint pain"],
     "This drug treats asthma, eczema, and nasal polyps by blocking IL-4 and IL-13 inflammation pathways."),
    ("omalizumab", ["Xolair"], "Biologic (Anti-IgE)", False,
     ["injection site reactions", "headache", "joint pain"],
     ["anaphylaxis (carry EpiPen)", "cancer risk (uncertain)"],
     "This drug treats severe allergic asthma by binding to IgE antibodies to prevent allergic reactions."),
    # ── GI / Acid ────────────────────────────────────────────────────────────
    ("omeprazole", ["Prilosec", "Zegerid"], "PPI", False,
     ["headache", "stomach pain", "nausea", "diarrhea"],
     ["C. diff infection", "bone fractures with long use", "low magnesium"],
     "This drug reduces stomach acid by blocking the proton pump in acid-producing cells."),
    ("pantoprazole", ["Protonix", "Pantoloc"], "PPI", False,
     ["headache", "diarrhea", "nausea", "stomach pain"],
     ["C. diff infection", "bone fractures with long use", "low magnesium"],
     "This drug blocks the proton pump to reduce stomach acid production."),
    ("esomeprazole", ["Nexium"], "PPI", False,
     ["headache", "nausea", "diarrhea", "stomach pain"],
     ["C. diff infection", "bone fractures", "low magnesium"],
     "This drug is the active form of omeprazole that blocks stomach acid production."),
    ("lansoprazole", ["Prevacid"], "PPI", False,
     ["diarrhea", "headache", "nausea", "stomach pain"],
     ["C. diff infection", "bone fractures", "low magnesium"],
     "This drug blocks the proton pump to heal ulcers and reduce acid reflux."),
    ("rabeprazole", ["Aciphex"], "PPI", False,
     ["headache", "diarrhea", "sore throat", "gas"],
     ["C. diff infection", "bone fractures", "low magnesium"],
     "This drug blocks the proton pump to reduce stomach acid and heal ulcers."),
    ("famotidine", ["Pepcid", "Zantac 360"], "H2 Blocker", False,
     ["headache", "dizziness", "constipation", "diarrhea"],
     ["liver problems", "blood cell changes"],
     "This drug reduces stomach acid by blocking H2 histamine receptors on acid-producing cells."),
    ("sucralfate", ["Carafate"], "Mucosal Protectant", False,
     ["constipation", "dry mouth", "nausea", "stomach upset"],
     ["bezoar formation", "aluminum toxicity in kidney disease"],
     "This drug coats and protects stomach ulcers by forming a protective barrier over damaged tissue."),
    ("misoprostol", ["Cytotec"], "Prostaglandin", True,
     ["diarrhea", "stomach pain", "nausea", "gas", "headache"],
     ["uterine rupture", "dangerous in pregnancy (causes contractions)"],
     "This drug protects the stomach lining and can induce uterine contractions."),
    ("ondansetron", ["Zofran", "Zuplenz"], "Antiemetic (5-HT3)", False,
     ["headache", "constipation", "fatigue", "dizziness"],
     ["QT prolongation (heart rhythm changes)", "serotonin syndrome"],
     "This drug prevents nausea and vomiting by blocking serotonin receptors in the brain and gut."),
    ("metoclopramide", ["Reglan"], "Prokinetic", False,
     ["drowsiness", "fatigue", "restlessness", "diarrhea"],
     ["tardive dyskinesia (involuntary movements)", "neuroleptic malignant syndrome"],
     "This drug speeds up stomach emptying and stops nausea by blocking dopamine receptors."),
    ("prochlorperazine", ["Compazine"], "Antiemetic", False,
     ["drowsiness", "dizziness", "dry mouth", "constipation"],
     ["tardive dyskinesia", "neuroleptic malignant syndrome"],
     "This drug treats nausea and vertigo by blocking dopamine receptors in the brain."),
    ("loperamide", ["Imodium"], "Antidiarrheal", False,
     ["constipation", "dizziness", "nausea", "stomach cramps"],
     ["fatal heart arrhythmias with overdose", "toxic megacolon"],
     "This drug slows gut movement to treat diarrhea by activating opioid receptors in the intestines."),
    ("polyethylene glycol", ["MiraLax", "GlycoLax"], "Osmotic Laxative", False,
     ["bloating", "gas", "nausea", "stomach cramps"],
     ["electrolyte imbalance", "dehydration"],
     "This drug draws water into the intestines to soften stool and relieve constipation."),
    ("bisacodyl", ["Dulcolax"], "Stimulant Laxative", False,
     ["stomach cramps", "diarrhea", "nausea"],
     ["electrolyte imbalance", "dependence with chronic use"],
     "This drug stimulates bowel movement by irritating the intestinal lining."),
    ("docusate", ["Colace", "Surfak"], "Stool Softener", False,
     ["stomach cramps", "diarrhea", "throat irritation"],
     ["electrolyte imbalance"],
     "This drug softens stool by helping water and fats mix into hard stool."),
    ("senna", ["Senokot", "Ex-Lax"], "Stimulant Laxative", False,
     ["stomach cramps", "diarrhea", "discolored urine"],
     ["electrolyte imbalance", "dependence with chronic use"],
     "This drug stimulates bowel contractions to relieve constipation."),
    ("lactulose", ["Enulose", "Kristalose"], "Osmotic Laxative", False,
     ["bloating", "gas", "stomach cramps", "diarrhea"],
     ["electrolyte imbalance", "dehydration"],
     "This drug draws water into the intestine and feeds beneficial gut bacteria to relieve constipation."),
    ("linaclotide", ["Linzess"], "GC-C Agonist", False,
     ["diarrhea", "stomach pain", "gas", "bloating"],
     ["severe diarrhea", "dehydration"],
     "This drug increases fluid in the intestines to relieve IBS-C and chronic constipation."),
    ("lubiprostone", ["Amitiza"], "Chloride Channel Activator", False,
     ["nausea", "diarrhea", "headache", "stomach pain"],
     ["shortness of breath", "severe diarrhea"],
     "This drug increases fluid secretion in the intestines by activating chloride channels."),
    # ── CNS / Psychiatry ─────────────────────────────────────────────────────
    ("sertraline", ["Zoloft"], "SSRI", False,
     ["nausea", "diarrhea", "insomnia", "dry mouth", "sweating"],
     ["suicidal thoughts in young adults", "serotonin syndrome", "increased bleeding"],
     "This drug treats depression by blocking serotonin reuptake in the brain."),
    ("escitalopram", ["Lexapro", "Cipralex"], "SSRI", False,
     ["nausea", "insomnia", "drowsiness", "dry mouth", "sweating"],
     ["suicidal thoughts in young adults", "serotonin syndrome", "QT prolongation"],
     "This drug treats depression and anxiety by selectively blocking serotonin reuptake."),
    ("fluoxetine", ["Prozac", "Sarafem"], "SSRI", False,
     ["nausea", "headache", "insomnia", "nervousness", "decreased appetite"],
     ["suicidal thoughts in young adults", "serotonin syndrome"],
     "This drug treats depression by blocking serotonin reuptake with a very long duration of action."),
    ("paroxetine", ["Paxil", "Brisdelle", "Pexeva"], "SSRI", False,
     ["drowsiness", "nausea", "dry mouth", "sweating", "sexual dysfunction"],
     ["suicidal thoughts in young adults", "serotonin syndrome", "severe withdrawal symptoms"],
     "This drug treats depression and anxiety by blocking serotonin reuptake."),
    ("citalopram", ["Celexa"], "SSRI", False,
     ["nausea", "dry mouth", "drowsiness", "insomnia", "sweating"],
     ["suicidal thoughts in young adults", "QT prolongation at high doses", "serotonin syndrome"],
     "This drug treats depression by selectively blocking serotonin reuptake."),
    ("fluvoxamine", ["Luvox"], "SSRI", False,
     ["nausea", "headache", "drowsiness", "insomnia", "diarrhea"],
     ["suicidal thoughts in young adults", "serotonin syndrome"],
     "This drug treats OCD and anxiety by blocking serotonin reuptake."),
    ("venlafaxine", ["Effexor", "Effexor XR"], "SNRI", False,
     ["nausea", "headache", "drowsiness", "dizziness", "dry mouth", "sweating"],
     ["high blood pressure at high doses", "serotonin syndrome", "severe withdrawal"],
     "This drug treats depression by blocking both serotonin and norepinephrine reuptake."),
    ("duloxetine", ["Cymbalta", "Drizalma"], "SNRI", False,
     ["nausea", "dry mouth", "constipation", "drowsiness", "fatigue"],
     ["liver damage", "serotonin syndrome", "suicidal thoughts in young adults"],
     "This drug treats depression and nerve pain by blocking serotonin and norepinephrine reuptake."),
    ("desvenlafaxine", ["Pristiq"], "SNRI", False,
     ["nausea", "dizziness", "insomnia", "sweating", "constipation"],
     ["high blood pressure", "serotonin syndrome", "suicidal thoughts"],
     "This drug is the active metabolite of venlafaxine that blocks serotonin and norepinephrine reuptake."),
    ("mirtazapine", ["Remeron"], "NaSSA", False,
     ["drowsiness", "weight gain", "increased appetite", "dry mouth", "dizziness"],
     ["agranulocytosis (dangerously low white cells)", "serotonin syndrome"],
     "This drug treats depression by increasing serotonin and norepinephrine through a unique receptor-blocking mechanism."),
    ("trazodone", ["Desyrel", "Oleptro"], "SARI", False,
     ["drowsiness", "dizziness", "dry mouth", "headache", "nausea"],
     ["priapism (prolonged painful erection)", "serotonin syndrome"],
     "This drug treats depression and insomnia by blocking serotonin reuptake and histamine receptors."),
    ("bupropion", ["Wellbutrin", "Zyban", "Aplenzin"], "NDRI", False,
     ["insomnia", "dry mouth", "nausea", "headache", "agitation"],
     ["seizures at high doses", "increased blood pressure"],
     "This drug treats depression and helps quit smoking by boosting dopamine and norepinephrine."),
    ("amitriptyline", ["Elavil"], "TCA", True,
     ["drowsiness", "dry mouth", "constipation", "weight gain", "blurred vision"],
     ["fatal heart arrhythmias with overdose", "seizures"],
     "This drug treats depression and chronic pain by blocking serotonin and norepinephrine reuptake."),
    ("nortriptyline", ["Pamelor", "Aventyl"], "TCA", True,
     ["drowsiness", "dry mouth", "constipation", "blurred vision"],
     ["fatal heart arrhythmias with overdose", "seizures"],
     "This drug treats depression and nerve pain by blocking norepinephrine reuptake."),
    ("imipramine", ["Tofranil"], "TCA", True,
     ["drowsiness", "dry mouth", "constipation", "weight gain", "dizziness"],
     ["fatal heart arrhythmias with overdose", "seizures"],
     "This drug treats depression by blocking serotonin and norepinephrine reuptake."),
    ("clomipramine", ["Anafranil"], "TCA", True,
     ["drowsiness", "dry mouth", "constipation", "weight gain", "tremor"],
     ["fatal heart arrhythmias with overdose", "seizures"],
     "This drug treats OCD by strongly blocking serotonin reuptake."),
    ("lithium", ["Lithobid", "Eskalith"], "Mood Stabilizer", True,
     ["tremor", "increased thirst", "frequent urination", "weight gain", "nausea"],
     ["kidney damage", "thyroid problems", "lithium toxicity (narrow safety range)"],
     "This drug stabilizes mood in bipolar disorder through multiple effects on brain signaling."),
    ("valproic acid", ["Depakote", "Depakene", "Stavzor"], "Mood Stabilizer/AED", True,
     ["nausea", "tremor", "weight gain", "drowsiness", "hair loss"],
     ["liver failure", "pancreatitis", "birth defects"],
     "This drug stabilizes mood and prevents seizures by increasing GABA and blocking sodium channels."),
    ("lamotrigine", ["Lamictal"], "Mood Stabilizer/AED", False,
     ["headache", "dizziness", "nausea", "blurred vision", "rash"],
     ["Stevens-Johnson syndrome (severe skin reaction)", "aseptic meningitis"],
     "This drug stabilizes mood and prevents seizures by blocking sodium channels."),
    ("carbamazepine", ["Tegretol", "Carbatrol", "Equetro"], "AED", True,
     ["dizziness", "drowsiness", "nausea", "vomiting", "unsteadiness"],
     ["Stevens-Johnson syndrome", "aplastic anemia", "liver damage"],
     "This drug prevents seizures and treats nerve pain by blocking sodium channels."),
    ("oxcarbazepine", ["Trileptal", "Oxtellar XR"], "AED", False,
     ["dizziness", "drowsiness", "headache", "nausea", "double vision"],
     ["severe skin reactions", "low sodium (hyponatremia)"],
     "This drug prevents seizures by blocking sodium channels with fewer drug interactions than carbamazepine."),
    ("phenytoin", ["Dilantin", "Phenytek"], "AED", True,
     ["dizziness", "drowsiness", "gum overgrowth", "excess hair growth", "nausea"],
     ["Stevens-Johnson syndrome", "liver failure", "blood disorders"],
     "This drug prevents seizures by stabilizing sodium channels in the brain."),
    ("phenobarbital", ["Luminal"], "AED/Barbiturate", True,
     ["drowsiness", "dizziness", "headache", "nausea"],
     ["respiratory depression", "dependence", "severe withdrawal seizures"],
     "This drug prevents seizures by enhancing GABA activity to calm the brain."),
    ("gabapentin", ["Neurontin", "Gralise"], "AED/Analgesic", False,
     ["drowsiness", "dizziness", "fatigue", "swelling", "unsteadiness"],
     ["suicidal thoughts", "respiratory depression with opioids"],
     "This drug treats nerve pain and seizures by modifying calcium channels in the brain."),
    ("pregabalin", ["Lyrica"], "AED/Analgesic", False,
     ["dizziness", "drowsiness", "weight gain", "dry mouth", "blurred vision"],
     ["suicidal thoughts", "angioedema", "dependence"],
     "This drug treats nerve pain, seizures, and anxiety by modifying calcium channels."),
    ("levetiracetam", ["Keppra", "Keppra XR"], "AED", False,
     ["drowsiness", "dizziness", "irritability", "weakness"],
     ["severe mood changes", "suicidal thoughts"],
     "This drug prevents seizures by binding to synaptic vesicle protein SV2A."),
    ("topiramate", ["Topamax", "Qudexy XR", "Trokendi XR"], "AED", False,
     ["tingling", "weight loss", "drowsiness", "difficulty concentrating", "taste changes"],
     ["kidney stones", "metabolic acidosis", "glaucoma"],
     "This drug prevents seizures and migraines by blocking sodium channels and enhancing GABA."),
    ("zonisamide", ["Zonegran"], "AED", False,
     ["drowsiness", "dizziness", "loss of appetite", "headache"],
     ["kidney stones", "metabolic acidosis", "heat stroke risk"],
     "This drug prevents seizures by blocking sodium and calcium channels."),
    ("lacosamide", ["Vimpat"], "AED", False,
     ["dizziness", "headache", "nausea", "double vision"],
     ["heart rhythm changes (PR prolongation)", "suicidal thoughts"],
     "This drug prevents seizures by enhancing slow inactivation of sodium channels."),
    ("aripiprazole", ["Abilify", "Aristada"], "Atypical Antipsychotic", False,
     ["restlessness", "insomnia", "nausea", "headache", "weight gain"],
     ["tardive dyskinesia", "neuroleptic malignant syndrome", "metabolic changes"],
     "This drug treats psychosis and mood disorders by partially activating dopamine receptors."),
    ("quetiapine", ["Seroquel", "Seroquel XR"], "Atypical Antipsychotic", False,
     ["drowsiness", "dry mouth", "dizziness", "weight gain", "constipation"],
     ["tardive dyskinesia", "metabolic syndrome (diabetes, high cholesterol)", "cataracts"],
     "This drug treats schizophrenia and bipolar disorder by blocking dopamine and serotonin receptors."),
    ("risperidone", ["Risperdal"], "Atypical Antipsychotic", False,
     ["drowsiness", "weight gain", "dizziness", "constipation", "dry mouth"],
     ["tardive dyskinesia", "high prolactin (breast enlargement)", "metabolic changes"],
     "This drug treats psychosis by blocking dopamine and serotonin receptors."),
    ("olanzapine", ["Zyprexa"], "Atypical Antipsychotic", False,
     ["weight gain", "drowsiness", "dizziness", "constipation", "dry mouth"],
     ["severe weight gain and diabetes", "tardive dyskinesia", "metabolic syndrome"],
     "This drug treats schizophrenia and bipolar disorder by blocking multiple neurotransmitter receptors."),
    ("clozapine", ["Clozaril", "Fazaclo"], "Atypical Antipsychotic", True,
     ["drowsiness", "weight gain", "drooling", "dizziness", "constipation"],
     ["agranulocytosis (requires blood monitoring)", "seizures", "myocarditis"],
     "This drug treats treatment-resistant schizophrenia by blocking dopamine and serotonin receptors."),
    ("ziprasidone", ["Geodon"], "Atypical Antipsychotic", False,
     ["drowsiness", "nausea", "dizziness", "restlessness"],
     ["QT prolongation", "tardive dyskinesia"],
     "This drug treats psychosis with less weight gain by blocking dopamine and serotonin receptors."),
    ("lurasidone", ["Latuda"], "Atypical Antipsychotic", False,
     ["drowsiness", "nausea", "restlessness", "movement disorders"],
     ["tardive dyskinesia", "neuroleptic malignant syndrome"],
     "This drug treats schizophrenia and bipolar depression by blocking dopamine and serotonin receptors."),
    ("paliperidone", ["Invega"], "Atypical Antipsychotic", False,
     ["drowsiness", "restlessness", "weight gain", "headache"],
     ["tardive dyskinesia", "high prolactin", "QT prolongation"],
     "This drug treats schizophrenia as the active metabolite of risperidone, available as a long-acting injection."),
    ("haloperidol", ["Haldol"], "Typical Antipsychotic", True,
     ["muscle rigidity", "tremor", "restlessness", "drowsiness"],
     ["tardive dyskinesia", "neuroleptic malignant syndrome", "QT prolongation"],
     "This drug treats severe psychosis by strongly blocking dopamine receptors."),
    ("alprazolam", ["Xanax"], "Benzodiazepine", True,
     ["drowsiness", "dizziness", "memory problems", "slurred speech"],
     ["respiratory depression", "dependence and withdrawal", "overdose risk"],
     "This drug reduces anxiety by enhancing GABA, the brain's calming chemical."),
    ("lorazepam", ["Ativan"], "Benzodiazepine", True,
     ["drowsiness", "dizziness", "weakness", "unsteadiness"],
     ["respiratory depression", "dependence and withdrawal"],
     "This drug reduces anxiety and seizures by enhancing GABA activity in the brain."),
    ("clonazepam", ["Klonopin"], "Benzodiazepine", True,
     ["drowsiness", "dizziness", "fatigue", "coordination problems"],
     ["respiratory depression", "severe dependence and withdrawal"],
     "This drug treats seizures and panic disorder by enhancing GABA activity."),
    ("diazepam", ["Valium"], "Benzodiazepine", True,
     ["drowsiness", "fatigue", "muscle weakness", "unsteadiness"],
     ["respiratory depression", "severe dependence", "paradoxical agitation"],
     "This drug treats anxiety, seizures, and muscle spasms by enhancing GABA activity."),
    ("temazepam", ["Restoril"], "Benzodiazepine", True,
     ["drowsiness", "dizziness", "fatigue", "nausea"],
     ["dependence", "complex sleep behaviors (sleepwalking)"],
     "This drug helps with sleep by enhancing GABA to induce sedation."),
    ("zolpidem", ["Ambien", "Edluar", "Intermezzo"], "Sedative-Hypnotic", True,
     ["drowsiness", "dizziness", "headache", "diarrhea"],
     ["complex sleep behaviors (sleep-driving)", "dependence", "falls"],
     "This drug helps with sleep by acting on GABA receptors specifically for sedation."),
    ("eszopiclone", ["Lunesta"], "Sedative-Hypnotic", True,
     ["unpleasant taste", "headache", "drowsiness", "dizziness"],
     ["complex sleep behaviors", "dependence"],
     "This drug induces sleep by acting on GABA receptors in the brain."),
    ("zaleplon", ["Sonata"], "Sedative-Hypnotic", True,
     ["headache", "dizziness", "drowsiness"],
     ["complex sleep behaviors", "dependence"],
     "This drug is an ultra-short-acting sleep aid that helps with falling asleep quickly."),
    ("hydroxyzine", ["Vistaril", "Atarax"], "Antihistamine/Anxiolytic", False,
     ["drowsiness", "dry mouth", "dizziness", "headache"],
     ["QT prolongation", "seizures"],
     "This drug reduces anxiety and itching by blocking histamine and acetylcholine receptors."),
    ("buspirone", ["Buspar"], "Anxiolytic", False,
     ["dizziness", "nausea", "headache", "nervousness", "lightheadedness"],
     ["serotonin syndrome when combined with other serotonergic drugs"],
     "This drug reduces anxiety by partially activating serotonin receptors without causing dependence."),
    ("clonidine", ["Catapres", "Kapvay"], "Alpha-2 Agonist", False,
     ["drowsiness", "dry mouth", "dizziness", "constipation"],
     ["rebound hypertension if stopped suddenly", "severe bradycardia"],
     "This drug activates alpha-2 receptors to lower blood pressure and reduce ADHD symptoms."),
    ("guanfacine", ["Tenex", "Intuniv"], "Alpha-2 Agonist", False,
     ["drowsiness", "fatigue", "dizziness", "dry mouth", "constipation"],
     ["rebound hypertension if stopped suddenly", "low blood pressure"],
     "This drug activates alpha-2 receptors to improve focus in ADHD and lower blood pressure."),
    ("methylphenidate", ["Ritalin", "Concerta", "Quillivant"], "Stimulant (ADHD)", True,
     ["decreased appetite", "insomnia", "headache", "stomach pain", "nervousness"],
     ["heart problems", "psychosis", "growth delay in children", "dependence"],
     "This drug treats ADHD by blocking dopamine and norepinephrine reuptake to improve focus."),
    ("amphetamine", ["Adderall", "Vyvanse", "Dexedrine"], "Stimulant (ADHD)", True,
     ["decreased appetite", "insomnia", "dry mouth", "increased heart rate", "anxiety"],
     ["heart attack", "psychosis", "severe dependence", "growth delay"],
     "This drug treats ADHD by increasing dopamine and norepinephrine release in the brain."),
    ("atomoxetine", ["Strattera"], "SNRI (ADHD)", False,
     ["decreased appetite", "nausea", "stomach pain", "fatigue", "dizziness"],
     ["suicidal thoughts in youth", "liver damage", "heart effects"],
     "This drug treats ADHD by blocking norepinephrine reuptake without stimulant effects."),
    ("modafinil", ["Provigil"], "Wakefulness Agent", False,
     ["headache", "nausea", "nervousness", "insomnia", "dizziness"],
     ["Stevens-Johnson syndrome", "psychiatric symptoms"],
     "This drug promotes wakefulness by affecting dopamine and other neurotransmitters."),
    ("baclofen", ["Lioresal", "Ozobax"], "Muscle Relaxant", False,
     ["drowsiness", "dizziness", "weakness", "nausea", "headache"],
     ["severe withdrawal seizures if stopped suddenly", "respiratory depression"],
     "This drug relaxes muscles by activating GABA-B receptors in the spinal cord."),
    ("cyclobenzaprine", ["Flexeril", "Amrix"], "Muscle Relaxant", False,
     ["drowsiness", "dry mouth", "dizziness", "fatigue"],
     ["serotonin syndrome", "heart rhythm changes"],
     "This drug relaxes muscles by acting on the brain stem rather than directly on muscles."),
    ("tizanidine", ["Zanaflex"], "Muscle Relaxant", False,
     ["drowsiness", "dry mouth", "dizziness", "weakness"],
     ["liver damage", "severe low blood pressure"],
     "This drug relaxes muscles by activating alpha-2 receptors in the spinal cord."),
    ("methocarbamol", ["Robaxin"], "Muscle Relaxant", False,
     ["drowsiness", "dizziness", "nausea", "blurred vision", "headache"],
     ["seizures with overdose", "severe allergic reaction"],
     "This drug relaxes muscles by depressing the central nervous system."),
    ("carisoprodol", ["Soma"], "Muscle Relaxant", True,
     ["drowsiness", "dizziness", "headache"],
     ["dependence and withdrawal", "seizures"],
     "This drug relaxes muscles and its metabolite (meprobamate) acts as a sedative."),
    # ── Endocrine / Thyroid ──────────────────────────────────────────────────
    ("levothyroxine", ["Synthroid", "Levoxyl", "Tirosint", "Unithroid"], "Thyroid Hormone", False,
     ["weight loss (initially)", "tremor", "rapid heartbeat", "sweating", "insomnia"],
     ["heart arrhythmias with excessive dose", "bone density loss"],
     "This drug replaces thyroid hormone to treat underactive thyroid."),
    ("liothyronine", ["Cytomel"], "Thyroid Hormone", False,
     ["rapid heartbeat", "tremor", "sweating", "headache"],
     ["heart arrhythmias", "angina"],
     "This drug provides fast-acting T3 thyroid hormone replacement."),
    ("methimazole", ["Tapazole"], "Antithyroid", False,
     ["rash", "joint pain", "nausea", "headache"],
     ["agranulocytosis (dangerously low white cells)", "liver damage"],
     "This drug treats overactive thyroid by blocking thyroid hormone production."),
    # ── Antibiotics / Antivirals / Antifungals ───────────────────────────────
    ("amoxicillin", ["Amoxil", "Trimox"], "Penicillin", False,
     ["nausea", "diarrhea", "stomach upset", "skin rash"],
     ["severe allergic reaction (anaphylaxis)", "C. diff infection"],
     "This drug kills bacteria by destroying their cell walls."),
    ("amoxicillin-clavulanate", ["Augmentin"], "Penicillin + BLI", False,
     ["diarrhea", "nausea", "vomiting", "rash"],
     ["liver damage", "severe allergic reaction", "C. diff infection"],
     "This drug combines amoxicillin with clavulanate to overcome antibiotic resistance."),
    ("azithromycin", ["Zithromax", "Z-Pack"], "Macrolide", False,
     ["nausea", "diarrhea", "stomach pain", "vomiting"],
     ["QT prolongation", "liver damage", "C. diff infection"],
     "This drug kills bacteria by blocking their ability to make proteins."),
    ("clarithromycin", ["Biaxin"], "Macrolide", False,
     ["nausea", "diarrhea", "taste changes", "headache"],
     ["QT prolongation", "liver damage"],
     "This drug kills bacteria by interrupting their protein production."),
    ("erythromycin", ["Ery-Tab", "Erythrocin"], "Macrolide", True,
     ["nausea", "vomiting", "diarrhea", "stomach cramps"],
     ["QT prolongation", "liver damage", "hearing loss"],
     "This drug kills bacteria by blocking their protein synthesis."),
    ("doxycycline", ["Vibramycin", "Doryx", "Monodox"], "Tetracycline", False,
     ["nausea", "sun sensitivity", "diarrhea", "stomach upset"],
     ["esophageal ulcer", "teeth staining in children", "C. diff infection"],
     "This drug kills bacteria by preventing them from making proteins."),
    ("minocycline", ["Minocin", "Solodyn"], "Tetracycline", False,
     ["dizziness", "nausea", "sun sensitivity", "skin discoloration"],
     ["autoimmune reactions", "liver damage", "vestibular toxicity"],
     "This drug kills bacteria by blocking protein synthesis and also reduces inflammation."),
    ("ciprofloxacin", ["Cipro"], "Fluoroquinolone", False,
     ["nausea", "diarrhea", "headache", "dizziness"],
     ["tendon rupture", "nerve damage (peripheral neuropathy)", "aortic aneurysm"],
     "This drug kills bacteria by blocking their DNA replication enzyme."),
    ("levofloxacin", ["Levaquin"], "Fluoroquinolone", False,
     ["nausea", "diarrhea", "headache", "insomnia"],
     ["tendon rupture", "nerve damage", "aortic aneurysm"],
     "This drug kills bacteria by inhibiting DNA gyrase and topoisomerase IV."),
    ("cephalexin", ["Keflex"], "Cephalosporin", False,
     ["diarrhea", "nausea", "stomach upset", "headache"],
     ["severe allergic reaction", "C. diff infection"],
     "This drug kills bacteria by disrupting their cell wall construction."),
    ("cefdinir", ["Omnicef"], "Cephalosporin", False,
     ["diarrhea", "nausea", "headache", "red-colored stool (harmless with iron)"],
     ["severe allergic reaction", "C. diff infection"],
     "This drug kills bacteria by blocking cell wall synthesis as a broad-spectrum cephalosporin."),
    ("ceftriaxone", ["Rocephin"], "Cephalosporin", False,
     ["diarrhea", "rash", "pain at injection site"],
     ["severe allergic reaction", "gallbladder sludge", "C. diff infection"],
     "This drug kills bacteria by blocking cell wall synthesis, given by injection."),
    ("clindamycin", ["Cleocin"], "Lincosamide", False,
     ["diarrhea", "nausea", "rash", "stomach pain"],
     ["C. diff infection (high risk)", "severe colitis"],
     "This drug kills bacteria by stopping their protein production."),
    ("metronidazole", ["Flagyl"], "Nitroimidazole", False,
     ["nausea", "headache", "metallic taste", "diarrhea", "stomach pain"],
     ["nerve damage with long use", "seizures"],
     "This drug kills certain bacteria and parasites by damaging their DNA."),
    ("trimethoprim-sulfamethoxazole", ["Bactrim", "Septra"], "Sulfonamide + TMP", False,
     ["nausea", "vomiting", "rash", "diarrhea"],
     ["Stevens-Johnson syndrome", "bone marrow suppression", "high potassium"],
     "This drug kills bacteria by blocking two steps in their folic acid production."),
    ("nitrofurantoin", ["Macrobid", "Macrodantin"], "Nitrofuran", False,
     ["nausea", "headache", "brown urine (harmless)", "stomach upset"],
     ["lung damage with chronic use", "liver damage", "nerve damage"],
     "This drug kills urinary tract bacteria by damaging their DNA and proteins."),
    ("vancomycin", ["Vancocin"], "Glycopeptide", True,
     ["nausea", "stomach pain", "red man syndrome (flushing with IV)"],
     ["kidney damage", "hearing loss", "blood cell changes"],
     "This drug kills resistant bacteria by blocking their cell wall construction."),
    ("linezolid", ["Zyvox"], "Oxazolidinone", True,
     ["nausea", "diarrhea", "headache", "insomnia"],
     ["bone marrow suppression", "serotonin syndrome", "nerve damage"],
     "This drug kills resistant bacteria by blocking the start of their protein production."),
    ("penicillin v", ["Pen-Vee K", "Veetids"], "Penicillin", False,
     ["nausea", "diarrhea", "stomach upset", "rash"],
     ["severe allergic reaction (anaphylaxis)", "C. diff infection"],
     "This drug kills bacteria by preventing them from building cell walls."),
    ("fluconazole", ["Diflucan"], "Antifungal (Azole)", False,
     ["headache", "nausea", "stomach pain", "diarrhea"],
     ["liver damage", "QT prolongation"],
     "This drug kills fungi by blocking an enzyme they need to build their cell membranes."),
    ("itraconazole", ["Sporanox"], "Antifungal (Azole)", True,
     ["nausea", "diarrhea", "stomach pain", "headache"],
     ["heart failure", "liver damage"],
     "This drug kills fungi by blocking ergosterol synthesis in fungal cell membranes."),
    ("voriconazole", ["Vfend"], "Antifungal (Azole)", True,
     ["visual disturbances", "rash", "nausea", "headache"],
     ["liver damage", "QT prolongation", "skin cancer with long use"],
     "This drug treats serious fungal infections by blocking ergosterol synthesis."),
    ("acyclovir", ["Zovirax"], "Antiviral (Herpes)", False,
     ["nausea", "headache", "diarrhea", "fatigue"],
     ["kidney damage", "neurological effects"],
     "This drug fights herpes viruses by blocking their DNA replication."),
    ("valacyclovir", ["Valtrex"], "Antiviral (Herpes)", False,
     ["headache", "nausea", "stomach pain", "dizziness"],
     ["kidney damage", "hallucinations in elderly"],
     "This drug is a prodrug of acyclovir that fights herpes viruses with better absorption."),
    ("oseltamivir", ["Tamiflu"], "Antiviral (Influenza)", False,
     ["nausea", "vomiting", "headache", "diarrhea"],
     ["neuropsychiatric effects", "severe allergic reaction"],
     "This drug treats influenza by blocking neuraminidase to prevent the virus from spreading."),
    # ── Rheumatology / Immunology ────────────────────────────────────────────
    ("methotrexate", ["Rheumatrex", "Trexall", "Otrexup"], "DMARD", True,
     ["nausea", "mouth sores", "fatigue", "stomach upset"],
     ["liver damage", "lung damage", "bone marrow suppression", "birth defects"],
     "This drug treats autoimmune diseases and cancer by blocking folic acid metabolism."),
    ("hydroxychloroquine", ["Plaquenil"], "DMARD", False,
     ["nausea", "headache", "dizziness", "diarrhea"],
     ["retinal toxicity (vision damage)", "heart rhythm changes"],
     "This drug modifies the immune system to treat lupus and rheumatoid arthritis."),
    ("sulfasalazine", ["Azulfidine"], "DMARD", False,
     ["nausea", "headache", "stomach upset", "orange urine"],
     ["blood disorders", "liver damage", "severe allergic reaction"],
     "This drug treats rheumatoid arthritis and ulcerative colitis by reducing inflammation."),
    ("leflunomide", ["Arava"], "DMARD", True,
     ["diarrhea", "nausea", "headache", "hair loss", "rash"],
     ["liver damage", "lung disease", "birth defects"],
     "This drug treats rheumatoid arthritis by blocking pyrimidine synthesis to suppress the immune system."),
    ("adalimumab", ["Humira"], "Biologic (Anti-TNF)", False,
     ["injection site reactions", "upper respiratory infections", "headache"],
     ["serious infections (TB)", "lymphoma risk", "heart failure worsening"],
     "This drug treats autoimmune diseases by blocking TNF-alpha inflammation."),
    ("etanercept", ["Enbrel"], "Biologic (Anti-TNF)", False,
     ["injection site reactions", "headache", "upper respiratory infections"],
     ["serious infections", "lymphoma risk", "nerve damage"],
     "This drug treats autoimmune diseases by binding TNF-alpha to reduce inflammation."),
    ("infliximab", ["Remicade"], "Biologic (Anti-TNF)", False,
     ["infusion reactions", "headache", "stomach pain"],
     ["serious infections (TB)", "lymphoma risk", "liver damage"],
     "This drug treats autoimmune diseases by neutralizing TNF-alpha through IV infusion."),
    ("tocilizumab", ["Actemra"], "Biologic (Anti-IL-6)", False,
     ["upper respiratory infections", "headache", "injection reactions"],
     ["serious infections", "liver damage", "GI perforation"],
     "This drug treats rheumatoid arthritis by blocking interleukin-6."),
    ("baricitinib", ["Olumiant"], "JAK Inhibitor", False,
     ["upper respiratory infections", "nausea", "herpes reactivation"],
     ["serious infections", "blood clots", "cancer risk"],
     "This drug treats rheumatoid arthritis by blocking JAK enzymes to reduce inflammation."),
    ("tofacitinib", ["Xeljanz"], "JAK Inhibitor", False,
     ["upper respiratory infections", "headache", "diarrhea"],
     ["serious infections", "blood clots", "cancer risk"],
     "This drug treats rheumatoid arthritis by inhibiting JAK kinases."),
    ("upadacitinib", ["Rinvoq"], "JAK Inhibitor", False,
     ["upper respiratory infections", "nausea", "cough", "acne"],
     ["serious infections", "blood clots", "cancer risk"],
     "This drug treats autoimmune diseases by selectively inhibiting JAK1."),
    ("ustekinumab", ["Stelara"], "Biologic (Anti-IL-12/23)", False,
     ["upper respiratory infections", "headache", "fatigue"],
     ["serious infections", "cancer risk"],
     "This drug treats psoriasis and Crohn's by blocking IL-12 and IL-23."),
    ("secukinumab", ["Cosentyx"], "Biologic (Anti-IL-17)", False,
     ["upper respiratory infections", "diarrhea", "injection site reactions"],
     ["serious infections", "inflammatory bowel disease"],
     "This drug treats psoriasis and arthritis by blocking interleukin-17A."),
    ("cyclosporine", ["Sandimmune", "Neoral", "Restasis"], "Immunosuppressant", True,
     ["tremor", "high blood pressure", "kidney problems", "excess hair growth"],
     ["kidney failure", "cancer risk", "serious infections"],
     "This drug suppresses the immune system by blocking T-cell activation to prevent organ rejection."),
    ("tacrolimus", ["Prograf", "Astagraf XL", "Envarsus"], "Immunosuppressant", True,
     ["tremor", "headache", "high blood pressure", "kidney problems", "diabetes"],
     ["kidney failure", "cancer risk", "serious infections"],
     "This drug prevents organ rejection by blocking T-cell activation more potently than cyclosporine."),
    ("mycophenolate", ["CellCept", "Myfortic"], "Immunosuppressant", True,
     ["nausea", "diarrhea", "vomiting", "stomach pain"],
     ["severe infections", "blood cell suppression", "birth defects"],
     "This drug prevents organ rejection by blocking immune cell proliferation."),
    # ── Urology / Sexual Health ──────────────────────────────────────────────
    ("tamsulosin", ["Flomax"], "Alpha Blocker", False,
     ["dizziness", "runny nose", "abnormal ejaculation", "headache"],
     ["severe low blood pressure", "floppy iris during eye surgery"],
     "This drug relaxes prostate and bladder muscles to improve urine flow."),
    ("doxazosin", ["Cardura"], "Alpha Blocker", False,
     ["dizziness", "fatigue", "headache", "low blood pressure"],
     ["first-dose fainting", "priapism"],
     "This drug relaxes muscles in the prostate and blood vessels to improve urine flow and lower blood pressure."),
    ("finasteride", ["Proscar", "Propecia"], "5-ARI", False,
     ["decreased sex drive", "erectile dysfunction", "decreased semen"],
     ["breast cancer (rare)", "depression"],
     "This drug shrinks the prostate and grows hair by blocking conversion of testosterone to DHT."),
    ("dutasteride", ["Avodart"], "5-ARI", False,
     ["decreased sex drive", "erectile dysfunction", "breast tenderness"],
     ["breast cancer (rare)", "birth defects if handled by pregnant women"],
     "This drug blocks both types of 5-alpha reductase to shrink the prostate more effectively."),
    ("sildenafil", ["Viagra", "Revatio"], "PDE-5 Inhibitor", False,
     ["headache", "flushing", "upset stomach", "nasal congestion", "vision changes"],
     ["sudden hearing loss", "priapism", "sudden vision loss"],
     "This drug treats erectile dysfunction by blocking PDE-5 to increase blood flow."),
    ("tadalafil", ["Cialis", "Adcirca"], "PDE-5 Inhibitor", False,
     ["headache", "muscle aches", "flushing", "nasal congestion", "back pain"],
     ["sudden hearing loss", "priapism", "sudden vision loss"],
     "This drug treats ED and enlarged prostate by blocking PDE-5 with a long 36-hour duration."),
    ("oxybutynin", ["Ditropan", "Oxytrol"], "Anticholinergic", False,
     ["dry mouth", "constipation", "drowsiness", "blurred vision", "dizziness"],
     ["heat stroke risk", "urinary retention", "confusion in elderly"],
     "This drug treats overactive bladder by blocking acetylcholine receptors on bladder muscle."),
    ("tolterodine", ["Detrol"], "Anticholinergic", False,
     ["dry mouth", "headache", "constipation", "dizziness"],
     ["urinary retention", "QT prolongation"],
     "This drug treats overactive bladder with less dry mouth than oxybutynin."),
    ("mirabegron", ["Myrbetriq"], "Beta-3 Agonist", False,
     ["high blood pressure", "urinary tract infection", "headache", "runny nose"],
     ["urinary retention", "severe high blood pressure"],
     "This drug relaxes the bladder by activating beta-3 receptors to reduce urgency."),
    # ── Osteoporosis / Bone ──────────────────────────────────────────────────
    ("alendronate", ["Fosamax"], "Bisphosphonate", False,
     ["stomach pain", "heartburn", "nausea", "constipation"],
     ["esophageal ulcer", "jaw bone death (osteonecrosis)", "atypical femur fracture"],
     "This drug strengthens bones by blocking osteoclasts from breaking down bone tissue."),
    ("risedronate", ["Actonel", "Atelvia"], "Bisphosphonate", False,
     ["stomach upset", "heartburn", "headache", "joint pain"],
     ["esophageal ulcer", "jaw bone death", "atypical femur fracture"],
     "This drug prevents bone loss by inhibiting osteoclast bone resorption."),
    ("ibandronate", ["Boniva"], "Bisphosphonate", False,
     ["stomach pain", "heartburn", "diarrhea"],
     ["jaw bone death", "atypical femur fracture", "esophageal ulcer"],
     "This drug prevents bone loss with monthly dosing by blocking osteoclast activity."),
    ("denosumab", ["Prolia", "Xgeva"], "RANKL Inhibitor", False,
     ["back pain", "joint pain", "muscle pain", "skin infections"],
     ["jaw bone death", "atypical femur fracture", "severe low calcium"],
     "This drug prevents bone loss by blocking RANKL to reduce osteoclast formation."),
    ("raloxifene", ["Evista"], "SERM", False,
     ["hot flashes", "leg cramps", "swelling", "joint pain"],
     ["blood clots (DVT, PE)", "stroke"],
     "This drug prevents osteoporosis in postmenopausal women by mimicking estrogen's effects on bone."),
    ("teriparatide", ["Forteo"], "PTH Analog", False,
     ["dizziness", "nausea", "leg cramps", "injection site pain"],
     ["osteosarcoma risk (in animals)", "high calcium"],
     "This drug builds new bone by mimicking parathyroid hormone to stimulate bone formation."),
    ("romosozumab", ["Evenity"], "Sclerostin Inhibitor", False,
     ["joint pain", "headache", "injection site reactions"],
     ["heart attack risk", "stroke risk", "jaw bone death"],
     "This drug builds bone and reduces bone loss by blocking sclerostin."),
    # ── Vitamins / Minerals ──────────────────────────────────────────────────
    ("folic acid", ["Folate", "Folacin"], "Vitamin B9", False,
     ["nausea", "bloating", "gas", "bitter taste"],
     ["allergic reaction (rare)", "may mask B12 deficiency"],
     "This vitamin supports DNA synthesis and red blood cell production."),
    ("cholecalciferol", ["Vitamin D3", "D-Vi-Sol"], "Vitamin D", False,
     ["nausea", "constipation", "weakness"],
     ["high calcium with excessive doses", "kidney stones"],
     "This vitamin helps the body absorb calcium to maintain strong bones."),
    ("ergocalciferol", ["Vitamin D2", "Drisdol"], "Vitamin D", False,
     ["nausea", "headache", "dry mouth", "metallic taste"],
     ["high calcium with excessive doses", "kidney damage"],
     "This plant-derived vitamin D helps the body absorb calcium."),
    ("calcium carbonate", ["Tums", "Os-Cal", "Caltrate"], "Calcium Supplement", False,
     ["constipation", "gas", "bloating", "stomach upset"],
     ["kidney stones", "high calcium levels"],
     "This supplement provides calcium for bone health and neutralizes stomach acid."),
    ("calcium citrate", ["Citracal"], "Calcium Supplement", False,
     ["nausea", "gas", "stomach upset"],
     ["kidney stones", "high calcium levels"],
     "This supplement provides easily absorbed calcium for people with low stomach acid."),
    ("ferrous sulfate", ["Slow FE", "Fer-In-Sol"], "Iron Supplement", False,
     ["constipation", "nausea", "stomach upset", "dark stools"],
     ["iron poisoning with overdose (especially in children)", "stomach ulcers"],
     "This supplement provides iron to treat iron deficiency anemia."),
    ("potassium chloride", ["Klor-Con", "K-Dur", "Micro-K"], "Electrolyte", False,
     ["nausea", "vomiting", "diarrhea", "stomach upset"],
     ["dangerously high potassium", "GI ulceration"],
     "This supplement replaces potassium lost from diuretics or other conditions."),
    ("magnesium oxide", ["Mag-Ox", "Uro-Mag"], "Electrolyte", False,
     ["diarrhea", "nausea", "stomach cramps"],
     ["high magnesium in kidney disease"],
     "This supplement provides magnesium for deficiency and acts as an antacid."),
    # ── Ophthalmology ────────────────────────────────────────────────────────
    ("latanoprost", ["Xalatan"], "Prostaglandin Analog (Eye)", False,
     ["eye redness", "eyelash growth", "eye color darkening", "stinging"],
     ["macular edema", "eye inflammation"],
     "This drug lowers eye pressure by increasing fluid drainage from the eye."),
    ("timolol", ["Timoptic"], "Beta Blocker (Eye)", False,
     ["eye stinging", "blurred vision", "headache"],
     ["bronchospasm", "slow heartbeat", "depression"],
     "This drug lowers eye pressure by reducing fluid production in the eye."),
    ("brimonidine", ["Alphagan"], "Alpha-2 Agonist (Eye)", False,
     ["eye redness", "dry mouth", "drowsiness", "blurred vision"],
     ["severe low blood pressure in children", "severe allergic reaction"],
     "This drug lowers eye pressure by reducing fluid production and increasing drainage."),
    ("dorzolamide", ["Trusopt"], "Carbonic Anhydrase Inhibitor (Eye)", False,
     ["eye stinging", "bitter taste", "blurred vision"],
     ["severe allergic reaction", "blood disorders"],
     "This drug lowers eye pressure by blocking carbonic anhydrase to reduce fluid production."),
    # ── Oncology (common orals) ──────────────────────────────────────────────
    ("tamoxifen", ["Nolvadex", "Soltamox"], "SERM (Oncology)", True,
     ["hot flashes", "nausea", "leg cramps", "vaginal discharge"],
     ["endometrial cancer", "blood clots", "stroke"],
     "This drug treats and prevents breast cancer by blocking estrogen receptors."),
    ("anastrozole", ["Arimidex"], "Aromatase Inhibitor", True,
     ["joint pain", "hot flashes", "weakness", "mood changes"],
     ["bone fractures", "cardiovascular events"],
     "This drug treats breast cancer by blocking the enzyme that makes estrogen."),
    ("letrozole", ["Femara"], "Aromatase Inhibitor", True,
     ["hot flashes", "joint pain", "fatigue", "sweating"],
     ["bone fractures", "cardiovascular events"],
     "This drug treats breast cancer by blocking aromatase to reduce estrogen levels."),
    ("imatinib", ["Gleevec"], "TKI", True,
     ["nausea", "muscle cramps", "diarrhea", "rash", "fatigue"],
     ["liver damage", "heart failure", "severe fluid retention"],
     "This drug treats certain cancers by blocking the abnormal tyrosine kinase protein."),
    ("ibrutinib", ["Imbruvica"], "BTK Inhibitor", True,
     ["diarrhea", "bruising", "fatigue", "muscle pain"],
     ["serious bleeding", "atrial fibrillation", "severe infections"],
     "This drug treats blood cancers by blocking Bruton's tyrosine kinase."),
    # ── HIV / Antiretrovirals ────────────────────────────────────────────────
    ("emtricitabine-tenofovir", ["Truvada", "Descovy"], "NRTI Combo", True,
     ["nausea", "headache", "diarrhea", "fatigue"],
     ["kidney damage", "bone density loss", "lactic acidosis"],
     "This drug combination prevents HIV replication by blocking reverse transcriptase."),
    ("bictegravir-emtricitabine-tenofovir", ["Biktarvy"], "NRTI+INSTI", True,
     ["headache", "nausea", "diarrhea"],
     ["kidney damage", "lactic acidosis"],
     "This drug treats HIV using three medications that block viral replication at multiple steps."),
    ("dolutegravir", ["Tivicay"], "INSTI", True,
     ["insomnia", "headache", "nausea"],
     ["liver damage", "immune reconstitution syndrome"],
     "This drug treats HIV by blocking integrase to prevent the virus from inserting DNA into cells."),
    ("ritonavir", ["Norvir", "Paxlovid"], "PI/Booster", True,
     ["nausea", "diarrhea", "vomiting", "taste changes"],
     ["liver damage", "pancreatitis", "heart rhythm changes"],
     "This drug boosts other HIV medications by blocking the enzyme that breaks them down."),
    # ── Dermatology ──────────────────────────────────────────────────────────
    ("tretinoin", ["Retin-A", "Renova", "Atralin"], "Retinoid", False,
     ["skin redness", "peeling", "dryness", "sun sensitivity", "stinging"],
     ["severe sunburn", "birth defects if taken orally"],
     "This drug treats acne by speeding up skin cell turnover to unclog pores."),
    ("isotretinoin", ["Accutane", "Claravis", "Absorica"], "Retinoid", True,
     ["dry lips", "dry skin", "dry eyes", "nosebleeds", "joint pain"],
     ["birth defects (iPLEDGE required)", "depression", "liver damage", "inflammatory bowel disease"],
     "This drug treats severe acne by shrinking oil glands and reducing skin oil production."),
    ("clobetasol", ["Temovate", "Clobex"], "Topical Corticosteroid (High Potency)", False,
     ["skin thinning", "burning", "stinging", "stretch marks"],
     ["adrenal suppression", "skin atrophy with prolonged use"],
     "This drug is an ultra-potent topical steroid that treats severe skin inflammation."),
    ("hydrocortisone", ["Cortaid", "Cortizone", "Hytone"], "Topical Corticosteroid", False,
     ["skin thinning", "burning", "itching"],
     ["adrenal suppression with large amounts", "skin infections"],
     "This drug is a mild topical steroid that treats minor skin inflammation and itching."),
    # ── Migraine ─────────────────────────────────────────────────────────────
    ("sumatriptan", ["Imitrex", "Zecuity", "Tosymra"], "Triptan", False,
     ["tingling", "flushing", "chest tightness", "drowsiness"],
     ["heart attack", "stroke", "serotonin syndrome"],
     "This drug treats migraines by narrowing blood vessels and blocking pain pathways in the brain."),
    ("rizatriptan", ["Maxalt"], "Triptan", False,
     ["dizziness", "drowsiness", "fatigue", "chest tightness"],
     ["heart attack", "stroke"],
     "This drug treats migraines by activating serotonin receptors to narrow blood vessels."),
    ("ubrogepant", ["Ubrelvy"], "CGRP Antagonist", False,
     ["nausea", "drowsiness", "dry mouth"],
     ["liver problems"],
     "This drug treats migraines by blocking CGRP receptors to reduce pain and inflammation."),
    ("rimegepant", ["Nurtec ODT"], "CGRP Antagonist", False,
     ["nausea", "stomach pain"],
     ["severe allergic reaction"],
     "This drug treats and prevents migraines by blocking CGRP receptors."),
    ("erenumab", ["Aimovig"], "CGRP mAb", False,
     ["injection site reactions", "constipation", "muscle cramps"],
     ["severe constipation", "high blood pressure"],
     "This drug prevents migraines by blocking the CGRP receptor with monthly injections."),
    ("fremanezumab", ["Ajovy"], "CGRP mAb", False,
     ["injection site reactions", "rash"],
     ["severe allergic reaction"],
     "This drug prevents migraines by neutralizing CGRP protein with monthly or quarterly injections."),
    # ── Sleep / OTC Misc ─────────────────────────────────────────────────────
    ("melatonin", ["Natrol", "ZzzQuil Pure Zzzs"], "Sleep Aid (OTC)", False,
     ["drowsiness", "headache", "dizziness", "nausea"],
     ["daytime grogginess", "hormone effects in children"],
     "This supplement helps regulate the sleep-wake cycle by mimicking the body's natural sleep hormone."),
    ("doxylamine", ["Unisom", "NyQuil"], "Sleep Aid (OTC)", False,
     ["drowsiness", "dry mouth", "dizziness", "constipation"],
     ["urinary retention", "confusion in elderly"],
     "This drug causes drowsiness by blocking histamine receptors to aid sleep."),
    ("zinc", ["Zicam", "Cold-Eeze"], "Mineral Supplement", False,
     ["nausea", "metallic taste", "stomach upset"],
     ["copper deficiency with chronic use"],
     "This mineral supports immune function and wound healing."),
    ("vitamin c", ["Ester-C", "Emergen-C"], "Vitamin", False,
     ["nausea", "stomach cramps", "diarrhea (at high doses)"],
     ["kidney stones with excessive doses"],
     "This vitamin supports immune function and acts as an antioxidant."),
]


# ── Build lookup tables ───────────────────────────────────────────────────────

# canonical_lower → DrugRecord
_CATALOG: dict[str, DrugRecord] = {}

# alias_lower (brand name, generic variant) → canonical_lower
_ALIAS_MAP: dict[str, str] = {}


def _build_tables() -> None:
    seen_canonicals: set[str] = set()
    for entry in _SEED:
        # Support both old 4-tuple and new 7-tuple format
        if len(entry) >= 7:
            canonical, brands, drug_class, high_risk, common_se, serious_se, mechanism = entry[:7]
        else:
            canonical, brands, drug_class, high_risk = entry[:4]
            common_se, serious_se, mechanism = [], [], ""
        key = canonical.lower()
        if key in seen_canonicals:
            continue
        seen_canonicals.add(key)
        rec = DrugRecord(
            canonical_name=canonical,
            brand_names=brands,
            drug_class=drug_class,
            is_high_risk=high_risk,
            common_side_effects=list(common_se),
            serious_side_effects=list(serious_se),
            mechanism_simple=mechanism,
        )
        _CATALOG[key] = rec
        for brand in brands:
            _ALIAS_MAP[brand.lower()] = key


_build_tables()


# ── Public API ────────────────────────────────────────────────────────────────

def find_drug(name: str) -> Optional[DrugRecord]:
    """
    Find a DrugRecord by any known name (canonical, brand, or RxNorm-normalised).

    Look-up order
    -------------
    1. Exact match on canonical name (case-insensitive)
    2. Brand/alias map
    3. RxNorm API normalisation (network call, cached via lru_cache)
    4. RxNorm approximate / spell-correct (network call, cached)

    Returns None only when no match is found by any method.

    Examples
    --------
    find_drug("Tylenol")    → DrugRecord(canonical_name="acetaminophen", ...)
    find_drug("lipitor")    → DrugRecord(canonical_name="atorvastatin", ...)
    find_drug("ibuprofin")  → DrugRecord(canonical_name="ibuprofen", ...) via spell-correct
    """
    key = (name or "").strip().lower()
    if not key:
        return None

    # 1. Direct catalog match
    if key in _CATALOG:
        return _CATALOG[key]

    # 2. Brand / alias map
    if key in _ALIAS_MAP:
        return _CATALOG.get(_ALIAS_MAP[key])

    # 3. RxNorm normalisation
    try:
        from rxnorm_client import normalize_drug_name
        canonical = normalize_drug_name(name)
        if canonical:
            c_key = canonical.lower()
            if c_key in _CATALOG:
                return _CATALOG[c_key]
            # Not in our catalog but RxNorm knows it — create a minimal record
            logger.info("[DrugCatalog] RxNorm resolved '%s' → '%s' (not in catalog)", name, canonical)
            return DrugRecord(canonical_name=canonical, drug_class="General")
    except Exception as exc:
        logger.debug("[DrugCatalog] RxNorm normalise failed for '%s': %s", name, exc)

    # 4. Approximate / spell-correct
    try:
        from rxnorm_client import spell_correct_drug
        corrected = spell_correct_drug(name)
        if corrected and corrected.lower() != key:
            logger.info("[DrugCatalog] Spell-corrected '%s' → '%s'", name, corrected)
            return find_drug(corrected)  # recurse once with corrected name
    except Exception as exc:
        logger.debug("[DrugCatalog] Spell-correct failed for '%s': %s", name, exc)

    return None


def is_known_drug(name: str) -> bool:
    """Return True if the name resolves to any known drug."""
    return find_drug(name) is not None


def is_high_risk(name: str) -> bool:
    """Return True if the drug is marked as high-risk / narrow therapeutic index."""
    rec = find_drug(name)
    return rec.is_high_risk if rec else False


def get_drug_class(name: str) -> Optional[str]:
    """Return the drug class string for a drug name, or None."""
    rec = find_drug(name)
    return rec.drug_class if rec else None


def get_side_effects(name: str) -> dict:
    """Return side effects and mechanism for a drug, or empty dict."""
    rec = find_drug(name)
    if not rec or not rec.common_side_effects:
        return {}
    return {
        "common": rec.common_side_effects,
        "serious": rec.serious_side_effects,
        "mechanism": rec.mechanism_simple,
    }


def catalog_size() -> int:
    """Return the number of canonical entries in the catalog."""
    return len(_CATALOG)


def preload_catalog(force: bool = False) -> dict:
    """
    Warm the RxNorm lru_cache for all top-catalog drugs.

    Makes one RxNorm API call per drug to fetch CUIs and stores canonical names.
    Safe to call at startup in a background thread.

    Parameters
    ----------
    force : bool
        If True, clears the lru_cache before fetching (triggers fresh network calls).

    Returns
    -------
    dict with keys: total, resolved, failed, elapsed_seconds
    """
    import time as _time
    try:
        from rxnorm_client import lookup_rxcui, get_canonical_name
        if force:
            lookup_rxcui.cache_clear()
            get_canonical_name.cache_clear()
    except ImportError:
        logger.warning("[DrugCatalog] rxnorm_client not available — skipping preload")
        return {"total": 0, "resolved": 0, "failed": 0, "elapsed_seconds": 0}

    start = _time.monotonic()
    resolved = 0
    failed = 0
    drugs = list(_CATALOG.keys())

    logger.info("[DrugCatalog] Preloading %d drugs from RxNorm...", len(drugs))
    for drug_name in drugs:
        try:
            rxcui = lookup_rxcui(drug_name)
            if rxcui:
                _CATALOG[drug_name].rxcui = rxcui
                resolved += 1
            else:
                failed += 1
        except Exception as exc:
            logger.debug("[DrugCatalog] Preload failed for '%s': %s", drug_name, exc)
            failed += 1

    elapsed = round(_time.monotonic() - start, 2)
    logger.info(
        "[DrugCatalog] Preload done — %d resolved, %d failed in %.1fs",
        resolved, failed, elapsed,
    )
    return {
        "total":            len(drugs),
        "resolved":         resolved,
        "failed":           failed,
        "elapsed_seconds":  elapsed,
    }
