"""
One-time script to populate the remaining _SEED drugs with side effects data.
Run once, copy output into drug_catalog.py, then delete this script.
"""

# Mapping: (canonical_name) -> ([common_se], [serious_se], mechanism_simple)
DRUG_DATA = {
    # ── Respiratory ──────────────────────────────────────────────────────────
    "albuterol": (["tremor", "nervousness", "rapid heartbeat", "headache"], ["severe allergic reaction", "paradoxical bronchospasm"], "This drug relaxes airway muscles quickly to relieve asthma and breathing difficulty."),
    "levalbuterol": (["tremor", "nervousness", "headache", "rapid heartbeat"], ["paradoxical bronchospasm", "chest pain"], "This drug is a purified form of albuterol that relaxes airway muscles with fewer heart side effects."),
    "salmeterol": (["headache", "sore throat", "nasal congestion", "cough"], ["asthma-related death if used alone", "paradoxical bronchospasm"], "This drug relaxes airway muscles for 12 hours to prevent asthma attacks."),
    "formoterol": (["tremor", "headache", "palpitations", "sore throat"], ["asthma-related death if used alone", "paradoxical bronchospasm"], "This drug is a fast-onset long-acting bronchodilator that keeps airways open for 12 hours."),
    "tiotropium": (["dry mouth", "constipation", "urinary retention", "blurred vision"], ["severe allergic reaction", "worsening glaucoma"], "This drug keeps airways open for 24 hours by blocking acetylcholine receptors in the lungs."),
    "umeclidinium": (["runny nose", "cough", "joint pain", "sore throat"], ["paradoxical bronchospasm", "worsening urinary retention"], "This drug is a long-acting anticholinergic that relaxes airways for 24 hours."),
    "ipratropium": (["dry mouth", "cough", "headache", "nausea"], ["paradoxical bronchospasm", "worsening glaucoma"], "This drug opens airways by blocking acetylcholine receptors in the lungs."),
    "fluticasone": (["sore throat", "hoarseness", "oral thrush", "headache", "nosebleed"], ["adrenal suppression with high doses", "bone density loss", "growth delay in children"], "This drug reduces airway inflammation by mimicking cortisol to suppress immune responses in the lungs."),
    "budesonide": (["sore throat", "headache", "nausea", "oral thrush"], ["adrenal suppression", "bone density loss"], "This drug reduces inflammation in the airways or gut by acting locally as a corticosteroid."),
    "beclomethasone": (["sore throat", "hoarseness", "oral thrush", "cough"], ["adrenal suppression", "bone density loss"], "This drug reduces airway inflammation as an inhaled corticosteroid."),
    "mometasone": (["headache", "sore throat", "nosebleed", "oral thrush"], ["adrenal suppression", "bone density loss"], "This drug reduces nasal or lung inflammation as a corticosteroid spray or inhaler."),
    "ciclesonide": (["headache", "nosebleed", "ear pain", "cough"], ["adrenal suppression", "bone density loss"], "This drug is a prodrug corticosteroid that activates in the lungs for targeted anti-inflammatory action."),
    "montelukast": (["headache", "stomach pain", "fatigue", "upper respiratory infection"], ["neuropsychiatric effects (mood changes, suicidal thoughts)", "liver problems"], "This drug blocks leukotrienes to reduce inflammation and mucus in the airways."),
    "roflumilast": (["diarrhea", "nausea", "headache", "weight loss"], ["psychiatric symptoms (depression, suicidal thoughts)", "weight loss"], "This drug reduces lung inflammation by blocking the PDE-4 enzyme."),
    "theophylline": (["nausea", "headache", "insomnia", "rapid heartbeat", "tremor"], ["seizures at high levels", "fatal heart arrhythmias"], "This drug opens airways and reduces inflammation by blocking phosphodiesterase and adenosine receptors."),
    "prednisone": (["weight gain", "mood changes", "insomnia", "increased appetite", "acne"], ["osteoporosis", "diabetes", "adrenal suppression", "severe infections"], "This drug suppresses the immune system and reduces inflammation by mimicking cortisol."),
    "methylprednisolone": (["nausea", "headache", "dizziness", "insomnia", "increased appetite"], ["osteoporosis", "adrenal suppression", "severe infections"], "This drug is a synthetic corticosteroid that powerfully reduces inflammation."),
    "dexamethasone": (["insomnia", "increased appetite", "mood changes", "flushing"], ["osteoporosis", "adrenal suppression", "hyperglycemia"], "This drug is a long-acting potent corticosteroid used to reduce severe inflammation."),
    "triamcinolone": (["injection site pain", "skin thinning", "headache", "nausea"], ["adrenal suppression", "osteoporosis"], "This drug reduces inflammation as an injectable or topical corticosteroid."),
    "cetirizine": (["drowsiness", "dry mouth", "fatigue", "headache"], ["severe allergic reaction"], "This drug blocks histamine receptors to relieve allergy symptoms with less sedation than older antihistamines."),
    "loratadine": (["headache", "dry mouth", "fatigue", "drowsiness"], ["severe allergic reaction"], "This drug blocks histamine to relieve allergy symptoms without significant drowsiness."),
    "fexofenadine": (["headache", "nausea", "dizziness"], ["severe allergic reaction"], "This drug blocks histamine receptors to treat allergies without crossing into the brain to cause drowsiness."),
    "desloratadine": (["sore throat", "dry mouth", "fatigue", "headache"], ["severe allergic reaction"], "This drug is an active metabolite of loratadine that blocks histamine with minimal sedation."),
    "levocetirizine": (["drowsiness", "dry mouth", "fatigue", "sore throat"], ["severe allergic reaction"], "This drug is the active form of cetirizine that blocks histamine receptors more potently."),
    "diphenhydramine": (["drowsiness", "dry mouth", "dizziness", "constipation", "blurred vision"], ["seizures with overdose", "urinary retention"], "This drug blocks histamine and crosses into the brain, causing sedation along with allergy relief."),
    "pseudoephedrine": (["trouble sleeping", "nervousness", "dizziness", "fast heartbeat", "headache"], ["severe high blood pressure", "stroke"], "This drug shrinks blood vessels in the nasal passages to relieve congestion."),
    "guaifenesin": (["nausea", "vomiting", "dizziness", "headache"], ["kidney stones with very high doses"], "This drug thins mucus in the airways to make coughs more productive."),
    "dextromethorphan": (["dizziness", "drowsiness", "nausea", "stomach upset"], ["serotonin syndrome with other drugs", "abuse potential"], "This drug suppresses cough by acting on the cough center in the brain."),
    "benralizumab": (["headache", "sore throat", "injection site reactions"], ["anaphylaxis", "parasitic infection worsening"], "This drug treats severe eosinophilic asthma by destroying eosinophils through anti-IL-5 receptor antibody action."),
    "mepolizumab": (["headache", "injection site reactions", "back pain", "fatigue"], ["anaphylaxis", "herpes zoster reactivation"], "This drug treats severe eosinophilic asthma by blocking interleukin-5."),
    "dupilumab": (["injection site reactions", "eye inflammation", "cold sores"], ["anaphylaxis", "joint pain"], "This drug treats asthma, eczema, and nasal polyps by blocking IL-4 and IL-13 inflammation pathways."),
    "omalizumab": (["injection site reactions", "headache", "joint pain"], ["anaphylaxis (carry EpiPen)", "cancer risk (uncertain)"], "This drug treats severe allergic asthma by binding to IgE antibodies to prevent allergic reactions."),
    # ── GI / Acid ────────────────────────────────────────────────────────────
    "omeprazole": (["headache", "stomach pain", "nausea", "diarrhea"], ["C. diff infection", "bone fractures with long use", "low magnesium"], "This drug reduces stomach acid by blocking the proton pump in acid-producing cells."),
    "pantoprazole": (["headache", "diarrhea", "nausea", "stomach pain"], ["C. diff infection", "bone fractures with long use", "low magnesium"], "This drug blocks the proton pump to reduce stomach acid production."),
    "esomeprazole": (["headache", "nausea", "diarrhea", "stomach pain"], ["C. diff infection", "bone fractures", "low magnesium"], "This drug is the active form of omeprazole that blocks stomach acid production."),
    "lansoprazole": (["diarrhea", "headache", "nausea", "stomach pain"], ["C. diff infection", "bone fractures", "low magnesium"], "This drug blocks the proton pump to heal ulcers and reduce acid reflux."),
    "rabeprazole": (["headache", "diarrhea", "sore throat", "gas"], ["C. diff infection", "bone fractures", "low magnesium"], "This drug blocks the proton pump to reduce stomach acid and heal ulcers."),
    "famotidine": (["headache", "dizziness", "constipation", "diarrhea"], ["liver problems", "blood cell changes"], "This drug reduces stomach acid by blocking H2 histamine receptors on acid-producing cells."),
    "sucralfate": (["constipation", "dry mouth", "nausea", "stomach upset"], ["bezoar formation", "aluminum toxicity in kidney disease"], "This drug coats and protects stomach ulcers by forming a protective barrier over damaged tissue."),
    "misoprostol": (["diarrhea", "stomach pain", "nausea", "gas", "headache"], ["uterine rupture", "dangerous in pregnancy (causes contractions)"], "This drug protects the stomach lining and can induce uterine contractions."),
    "ondansetron": (["headache", "constipation", "fatigue", "dizziness"], ["QT prolongation (heart rhythm changes)", "serotonin syndrome"], "This drug prevents nausea and vomiting by blocking serotonin receptors in the brain and gut."),
    "metoclopramide": (["drowsiness", "fatigue", "restlessness", "diarrhea"], ["tardive dyskinesia (involuntary movements)", "neuroleptic malignant syndrome"], "This drug speeds up stomach emptying and stops nausea by blocking dopamine receptors."),
    "prochlorperazine": (["drowsiness", "dizziness", "dry mouth", "constipation"], ["tardive dyskinesia", "neuroleptic malignant syndrome"], "This drug treats nausea and vertigo by blocking dopamine receptors in the brain."),
    "loperamide": (["constipation", "dizziness", "nausea", "stomach cramps"], ["fatal heart arrhythmias with overdose", "toxic megacolon"], "This drug slows gut movement to treat diarrhea by activating opioid receptors in the intestines."),
    "polyethylene glycol": (["bloating", "gas", "nausea", "stomach cramps"], ["electrolyte imbalance", "dehydration"], "This drug draws water into the intestines to soften stool and relieve constipation."),
    "bisacodyl": (["stomach cramps", "diarrhea", "nausea"], ["electrolyte imbalance", "dependence with chronic use"], "This drug stimulates bowel movement by irritating the intestinal lining."),
    "docusate": (["stomach cramps", "diarrhea", "throat irritation"], ["electrolyte imbalance"], "This drug softens stool by helping water and fats mix into hard stool."),
    "senna": (["stomach cramps", "diarrhea", "discolored urine"], ["electrolyte imbalance", "dependence with chronic use"], "This drug stimulates bowel contractions to relieve constipation."),
    "lactulose": (["bloating", "gas", "stomach cramps", "diarrhea"], ["electrolyte imbalance", "dehydration"], "This drug draws water into the intestine and feeds beneficial gut bacteria to relieve constipation."),
    "linaclotide": (["diarrhea", "stomach pain", "gas", "bloating"], ["severe diarrhea", "dehydration"], "This drug increases fluid in the intestines to relieve IBS-C and chronic constipation."),
    "lubiprostone": (["nausea", "diarrhea", "headache", "stomach pain"], ["shortness of breath", "severe diarrhea"], "This drug increases fluid secretion in the intestines by activating chloride channels."),
    # ── CNS / Psychiatry ─────────────────────────────────────────────────────
    "sertraline": (["nausea", "diarrhea", "insomnia", "dry mouth", "sweating"], ["suicidal thoughts in young adults", "serotonin syndrome", "increased bleeding"], "This drug treats depression by blocking serotonin reuptake in the brain."),
    "escitalopram": (["nausea", "insomnia", "drowsiness", "dry mouth", "sweating"], ["suicidal thoughts in young adults", "serotonin syndrome", "QT prolongation"], "This drug treats depression and anxiety by selectively blocking serotonin reuptake."),
    "fluoxetine": (["nausea", "headache", "insomnia", "nervousness", "decreased appetite"], ["suicidal thoughts in young adults", "serotonin syndrome"], "This drug treats depression by blocking serotonin reuptake with a very long duration of action."),
    "paroxetine": (["drowsiness", "nausea", "dry mouth", "sweating", "sexual dysfunction"], ["suicidal thoughts in young adults", "serotonin syndrome", "severe withdrawal symptoms"], "This drug treats depression and anxiety by blocking serotonin reuptake."),
    "citalopram": (["nausea", "dry mouth", "drowsiness", "insomnia", "sweating"], ["suicidal thoughts in young adults", "QT prolongation at high doses", "serotonin syndrome"], "This drug treats depression by selectively blocking serotonin reuptake."),
    "fluvoxamine": (["nausea", "headache", "drowsiness", "insomnia", "diarrhea"], ["suicidal thoughts in young adults", "serotonin syndrome"], "This drug treats OCD and anxiety by blocking serotonin reuptake."),
    "venlafaxine": (["nausea", "headache", "drowsiness", "dizziness", "dry mouth", "sweating"], ["high blood pressure at high doses", "serotonin syndrome", "severe withdrawal"], "This drug treats depression by blocking both serotonin and norepinephrine reuptake."),
    "duloxetine": (["nausea", "dry mouth", "constipation", "drowsiness", "fatigue"], ["liver damage", "serotonin syndrome", "suicidal thoughts in young adults"], "This drug treats depression and nerve pain by blocking serotonin and norepinephrine reuptake."),
    "desvenlafaxine": (["nausea", "dizziness", "insomnia", "sweating", "constipation"], ["high blood pressure", "serotonin syndrome", "suicidal thoughts"], "This drug is the active metabolite of venlafaxine that blocks serotonin and norepinephrine reuptake."),
    "mirtazapine": (["drowsiness", "weight gain", "increased appetite", "dry mouth", "dizziness"], ["agranulocytosis (dangerously low white cells)", "serotonin syndrome"], "This drug treats depression by increasing serotonin and norepinephrine through a unique receptor-blocking mechanism."),
    "trazodone": (["drowsiness", "dizziness", "dry mouth", "headache", "nausea"], ["priapism (prolonged painful erection)", "serotonin syndrome"], "This drug treats depression and insomnia by blocking serotonin reuptake and histamine receptors."),
    "bupropion": (["insomnia", "dry mouth", "nausea", "headache", "agitation"], ["seizures at high doses", "increased blood pressure"], "This drug treats depression and helps quit smoking by boosting dopamine and norepinephrine."),
    "amitriptyline": (["drowsiness", "dry mouth", "constipation", "weight gain", "blurred vision"], ["fatal heart arrhythmias with overdose", "seizures"], "This drug treats depression and chronic pain by blocking serotonin and norepinephrine reuptake."),
    "nortriptyline": (["drowsiness", "dry mouth", "constipation", "blurred vision"], ["fatal heart arrhythmias with overdose", "seizures"], "This drug treats depression and nerve pain by blocking norepinephrine reuptake."),
    "imipramine": (["drowsiness", "dry mouth", "constipation", "weight gain", "dizziness"], ["fatal heart arrhythmias with overdose", "seizures"], "This drug treats depression by blocking serotonin and norepinephrine reuptake."),
    "clomipramine": (["drowsiness", "dry mouth", "constipation", "weight gain", "tremor"], ["fatal heart arrhythmias with overdose", "seizures"], "This drug treats OCD by strongly blocking serotonin reuptake."),
    "lithium": (["tremor", "increased thirst", "frequent urination", "weight gain", "nausea"], ["kidney damage", "thyroid problems", "lithium toxicity (narrow safety range)"], "This drug stabilizes mood in bipolar disorder through multiple effects on brain signaling."),
    "valproic acid": (["nausea", "tremor", "weight gain", "drowsiness", "hair loss"], ["liver failure", "pancreatitis", "birth defects"], "This drug stabilizes mood and prevents seizures by increasing GABA and blocking sodium channels."),
    "lamotrigine": (["headache", "dizziness", "nausea", "blurred vision", "rash"], ["Stevens-Johnson syndrome (severe skin reaction)", "aseptic meningitis"], "This drug stabilizes mood and prevents seizures by blocking sodium channels."),
    "carbamazepine": (["dizziness", "drowsiness", "nausea", "vomiting", "unsteadiness"], ["Stevens-Johnson syndrome", "aplastic anemia", "liver damage"], "This drug prevents seizures and treats nerve pain by blocking sodium channels."),
    "oxcarbazepine": (["dizziness", "drowsiness", "headache", "nausea", "double vision"], ["severe skin reactions", "low sodium (hyponatremia)"], "This drug prevents seizures by blocking sodium channels with fewer drug interactions than carbamazepine."),
    "phenytoin": (["dizziness", "drowsiness", "gum overgrowth", "excess hair growth", "nausea"], ["Stevens-Johnson syndrome", "liver failure", "blood disorders"], "This drug prevents seizures by stabilizing sodium channels in the brain."),
    "phenobarbital": (["drowsiness", "dizziness", "headache", "nausea"], ["respiratory depression", "dependence", "severe withdrawal seizures"], "This drug prevents seizures by enhancing GABA activity to calm the brain."),
    "gabapentin": (["drowsiness", "dizziness", "fatigue", "swelling", "unsteadiness"], ["suicidal thoughts", "respiratory depression with opioids"], "This drug treats nerve pain and seizures by modifying calcium channels in the brain."),
    "pregabalin": (["dizziness", "drowsiness", "weight gain", "dry mouth", "blurred vision"], ["suicidal thoughts", "angioedema", "dependence"], "This drug treats nerve pain, seizures, and anxiety by modifying calcium channels."),
    "levetiracetam": (["drowsiness", "dizziness", "irritability", "weakness"], ["severe mood changes", "suicidal thoughts"], "This drug prevents seizures by binding to synaptic vesicle protein SV2A."),
    "topiramate": (["tingling", "weight loss", "drowsiness", "difficulty concentrating", "taste changes"], ["kidney stones", "metabolic acidosis", "glaucoma"], "This drug prevents seizures and migraines by blocking sodium channels and enhancing GABA."),
    "zonisamide": (["drowsiness", "dizziness", "loss of appetite", "headache"], ["kidney stones", "metabolic acidosis", "heat stroke risk"], "This drug prevents seizures by blocking sodium and calcium channels."),
    "lacosamide": (["dizziness", "headache", "nausea", "double vision"], ["heart rhythm changes (PR prolongation)", "suicidal thoughts"], "This drug prevents seizures by enhancing slow inactivation of sodium channels."),
    "aripiprazole": (["restlessness", "insomnia", "nausea", "headache", "weight gain"], ["tardive dyskinesia", "neuroleptic malignant syndrome", "metabolic changes"], "This drug treats psychosis and mood disorders by partially activating dopamine receptors."),
    "quetiapine": (["drowsiness", "dry mouth", "dizziness", "weight gain", "constipation"], ["tardive dyskinesia", "metabolic syndrome (diabetes, high cholesterol)", "cataracts"], "This drug treats schizophrenia and bipolar disorder by blocking dopamine and serotonin receptors."),
    "risperidone": (["drowsiness", "weight gain", "dizziness", "constipation", "dry mouth"], ["tardive dyskinesia", "high prolactin (breast enlargement)", "metabolic changes"], "This drug treats psychosis by blocking dopamine and serotonin receptors."),
    "olanzapine": (["weight gain", "drowsiness", "dizziness", "constipation", "dry mouth"], ["severe weight gain and diabetes", "tardive dyskinesia", "metabolic syndrome"], "This drug treats schizophrenia and bipolar disorder by blocking multiple neurotransmitter receptors."),
    "clozapine": (["drowsiness", "weight gain", "drooling", "dizziness", "constipation"], ["agranulocytosis (requires blood monitoring)", "seizures", "myocarditis"], "This drug treats treatment-resistant schizophrenia by blocking dopamine and serotonin receptors."),
    "ziprasidone": (["drowsiness", "nausea", "dizziness", "restlessness"], ["QT prolongation", "tardive dyskinesia"], "This drug treats psychosis with less weight gain by blocking dopamine and serotonin receptors."),
    "lurasidone": (["drowsiness", "nausea", "restlessness", "movement disorders"], ["tardive dyskinesia", "neuroleptic malignant syndrome"], "This drug treats schizophrenia and bipolar depression by blocking dopamine and serotonin receptors."),
    "paliperidone": (["drowsiness", "restlessness", "weight gain", "headache"], ["tardive dyskinesia", "high prolactin", "QT prolongation"], "This drug treats schizophrenia as the active metabolite of risperidone, available as a long-acting injection."),
    "haloperidol": (["muscle rigidity", "tremor", "restlessness", "drowsiness"], ["tardive dyskinesia", "neuroleptic malignant syndrome", "QT prolongation"], "This drug treats severe psychosis by strongly blocking dopamine receptors."),
    "alprazolam": (["drowsiness", "dizziness", "memory problems", "slurred speech"], ["respiratory depression", "dependence and withdrawal", "overdose risk"], "This drug reduces anxiety by enhancing GABA, the brain's calming chemical."),
    "lorazepam": (["drowsiness", "dizziness", "weakness", "unsteadiness"], ["respiratory depression", "dependence and withdrawal"], "This drug reduces anxiety and seizures by enhancing GABA activity in the brain."),
    "clonazepam": (["drowsiness", "dizziness", "fatigue", "coordination problems"], ["respiratory depression", "severe dependence and withdrawal"], "This drug treats seizures and panic disorder by enhancing GABA activity."),
    "diazepam": (["drowsiness", "fatigue", "muscle weakness", "unsteadiness"], ["respiratory depression", "severe dependence", "paradoxical agitation"], "This drug treats anxiety, seizures, and muscle spasms by enhancing GABA activity."),
    "temazepam": (["drowsiness", "dizziness", "fatigue", "nausea"], ["dependence", "complex sleep behaviors (sleepwalking)"], "This drug helps with sleep by enhancing GABA to induce sedation."),
    "zolpidem": (["drowsiness", "dizziness", "headache", "diarrhea"], ["complex sleep behaviors (sleep-driving)", "dependence", "falls"], "This drug helps with sleep by acting on GABA receptors specifically for sedation."),
    "eszopiclone": (["unpleasant taste", "headache", "drowsiness", "dizziness"], ["complex sleep behaviors", "dependence"], "This drug induces sleep by acting on GABA receptors in the brain."),
    "zaleplon": (["headache", "dizziness", "drowsiness"], ["complex sleep behaviors", "dependence"], "This drug is an ultra-short-acting sleep aid that helps with falling asleep quickly."),
    "hydroxyzine": (["drowsiness", "dry mouth", "dizziness", "headache"], ["QT prolongation", "seizures"], "This drug reduces anxiety and itching by blocking histamine and acetylcholine receptors."),
    "buspirone": (["dizziness", "nausea", "headache", "nervousness", "lightheadedness"], ["serotonin syndrome when combined with other serotonergic drugs"], "This drug reduces anxiety by partially activating serotonin receptors without causing dependence."),
    "clonidine": (["drowsiness", "dry mouth", "dizziness", "constipation"], ["rebound hypertension if stopped suddenly", "severe bradycardia"], "This drug activates alpha-2 receptors to lower blood pressure and reduce ADHD symptoms."),
    "guanfacine": (["drowsiness", "fatigue", "dizziness", "dry mouth", "constipation"], ["rebound hypertension if stopped suddenly", "low blood pressure"], "This drug activates alpha-2 receptors to improve focus in ADHD and lower blood pressure."),
    "methylphenidate": (["decreased appetite", "insomnia", "headache", "stomach pain", "nervousness"], ["heart problems", "psychosis", "growth delay in children", "dependence"], "This drug treats ADHD by blocking dopamine and norepinephrine reuptake to improve focus."),
    "amphetamine": (["decreased appetite", "insomnia", "dry mouth", "increased heart rate", "anxiety"], ["heart attack", "psychosis", "severe dependence", "growth delay"], "This drug treats ADHD by increasing dopamine and norepinephrine release in the brain."),
    "atomoxetine": (["decreased appetite", "nausea", "stomach pain", "fatigue", "dizziness"], ["suicidal thoughts in youth", "liver damage", "heart effects"], "This drug treats ADHD by blocking norepinephrine reuptake without stimulant effects."),
    "modafinil": (["headache", "nausea", "nervousness", "insomnia", "dizziness"], ["Stevens-Johnson syndrome", "psychiatric symptoms"], "This drug promotes wakefulness by affecting dopamine and other neurotransmitters."),
    "baclofen": (["drowsiness", "dizziness", "weakness", "nausea", "headache"], ["severe withdrawal seizures if stopped suddenly", "respiratory depression"], "This drug relaxes muscles by activating GABA-B receptors in the spinal cord."),
    "cyclobenzaprine": (["drowsiness", "dry mouth", "dizziness", "fatigue"], ["serotonin syndrome", "heart rhythm changes"], "This drug relaxes muscles by acting on the brain stem rather than directly on muscles."),
    "tizanidine": (["drowsiness", "dry mouth", "dizziness", "weakness"], ["liver damage", "severe low blood pressure"], "This drug relaxes muscles by activating alpha-2 receptors in the spinal cord."),
    "methocarbamol": (["drowsiness", "dizziness", "nausea", "blurred vision", "headache"], ["seizures with overdose", "severe allergic reaction"], "This drug relaxes muscles by depressing the central nervous system."),
    "carisoprodol": (["drowsiness", "dizziness", "headache"], ["dependence and withdrawal", "seizures"], "This drug relaxes muscles and its metabolite (meprobamate) acts as a sedative."),
    # ── Endocrine / Thyroid ──────────────────────────────────────────────────
    "levothyroxine": (["weight loss (initially)", "tremor", "rapid heartbeat", "sweating", "insomnia"], ["heart arrhythmias with excessive dose", "bone density loss"], "This drug replaces thyroid hormone to treat underactive thyroid."),
    "liothyronine": (["rapid heartbeat", "tremor", "sweating", "headache"], ["heart arrhythmias", "angina"], "This drug provides fast-acting T3 thyroid hormone replacement."),
    "methimazole": (["rash", "joint pain", "nausea", "headache"], ["agranulocytosis (dangerously low white cells)", "liver damage"], "This drug treats overactive thyroid by blocking thyroid hormone production."),
    # ── Antibiotics / Antivirals / Antifungals ───────────────────────────────
    "amoxicillin": (["nausea", "diarrhea", "stomach upset", "skin rash"], ["severe allergic reaction (anaphylaxis)", "C. diff infection"], "This drug kills bacteria by destroying their cell walls."),
    "amoxicillin-clavulanate": (["diarrhea", "nausea", "vomiting", "rash"], ["liver damage", "severe allergic reaction", "C. diff infection"], "This drug combines amoxicillin with clavulanate to overcome antibiotic resistance."),
    "azithromycin": (["nausea", "diarrhea", "stomach pain", "vomiting"], ["QT prolongation", "liver damage", "C. diff infection"], "This drug kills bacteria by blocking their ability to make proteins."),
    "clarithromycin": (["nausea", "diarrhea", "taste changes", "headache"], ["QT prolongation", "liver damage"], "This drug kills bacteria by interrupting their protein production."),
    "erythromycin": (["nausea", "vomiting", "diarrhea", "stomach cramps"], ["QT prolongation", "liver damage", "hearing loss"], "This drug kills bacteria by blocking their protein synthesis."),
    "doxycycline": (["nausea", "sun sensitivity", "diarrhea", "stomach upset"], ["esophageal ulcer", "teeth staining in children", "C. diff infection"], "This drug kills bacteria by preventing them from making proteins."),
    "minocycline": (["dizziness", "nausea", "sun sensitivity", "skin discoloration"], ["autoimmune reactions", "liver damage", "vestibular toxicity"], "This drug kills bacteria by blocking protein synthesis and also reduces inflammation."),
    "ciprofloxacin": (["nausea", "diarrhea", "headache", "dizziness"], ["tendon rupture", "nerve damage (peripheral neuropathy)", "aortic aneurysm"], "This drug kills bacteria by blocking their DNA replication enzyme."),
    "levofloxacin": (["nausea", "diarrhea", "headache", "insomnia"], ["tendon rupture", "nerve damage", "aortic aneurysm"], "This drug kills bacteria by inhibiting DNA gyrase and topoisomerase IV."),
    "cephalexin": (["diarrhea", "nausea", "stomach upset", "headache"], ["severe allergic reaction", "C. diff infection"], "This drug kills bacteria by disrupting their cell wall construction."),
    "cefdinir": (["diarrhea", "nausea", "headache", "red-colored stool (harmless with iron)"], ["severe allergic reaction", "C. diff infection"], "This drug kills bacteria by blocking cell wall synthesis as a broad-spectrum cephalosporin."),
    "ceftriaxone": (["diarrhea", "rash", "pain at injection site"], ["severe allergic reaction", "gallbladder sludge", "C. diff infection"], "This drug kills bacteria by blocking cell wall synthesis, given by injection."),
    "clindamycin": (["diarrhea", "nausea", "rash", "stomach pain"], ["C. diff infection (high risk)", "severe colitis"], "This drug kills bacteria by stopping their protein production."),
    "metronidazole": (["nausea", "headache", "metallic taste", "diarrhea", "stomach pain"], ["nerve damage with long use", "seizures"], "This drug kills certain bacteria and parasites by damaging their DNA."),
    "trimethoprim-sulfamethoxazole": (["nausea", "vomiting", "rash", "diarrhea"], ["Stevens-Johnson syndrome", "bone marrow suppression", "high potassium"], "This drug kills bacteria by blocking two steps in their folic acid production."),
    "nitrofurantoin": (["nausea", "headache", "brown urine (harmless)", "stomach upset"], ["lung damage with chronic use", "liver damage", "nerve damage"], "This drug kills urinary tract bacteria by damaging their DNA and proteins."),
    "vancomycin": (["nausea", "stomach pain", "red man syndrome (flushing with IV)"], ["kidney damage", "hearing loss", "blood cell changes"], "This drug kills resistant bacteria by blocking their cell wall construction."),
    "linezolid": (["nausea", "diarrhea", "headache", "insomnia"], ["bone marrow suppression", "serotonin syndrome", "nerve damage"], "This drug kills resistant bacteria by blocking the start of their protein production."),
    "penicillin v": (["nausea", "diarrhea", "stomach upset", "rash"], ["severe allergic reaction (anaphylaxis)", "C. diff infection"], "This drug kills bacteria by preventing them from building cell walls."),
    "fluconazole": (["headache", "nausea", "stomach pain", "diarrhea"], ["liver damage", "QT prolongation"], "This drug kills fungi by blocking an enzyme they need to build their cell membranes."),
    "itraconazole": (["nausea", "diarrhea", "stomach pain", "headache"], ["heart failure", "liver damage"], "This drug kills fungi by blocking ergosterol synthesis in fungal cell membranes."),
    "voriconazole": (["visual disturbances", "rash", "nausea", "headache"], ["liver damage", "QT prolongation", "skin cancer with long use"], "This drug treats serious fungal infections by blocking ergosterol synthesis."),
    "acyclovir": (["nausea", "headache", "diarrhea", "fatigue"], ["kidney damage", "neurological effects"], "This drug fights herpes viruses by blocking their DNA replication."),
    "valacyclovir": (["headache", "nausea", "stomach pain", "dizziness"], ["kidney damage", "hallucinations in elderly"], "This drug is a prodrug of acyclovir that fights herpes viruses with better absorption."),
    "oseltamivir": (["nausea", "vomiting", "headache", "diarrhea"], ["neuropsychiatric effects", "severe allergic reaction"], "This drug treats influenza by blocking neuraminidase to prevent the virus from spreading."),
    # ── Rheumatology / Immunology ────────────────────────────────────────────
    "methotrexate": (["nausea", "mouth sores", "fatigue", "stomach upset"], ["liver damage", "lung damage", "bone marrow suppression", "birth defects"], "This drug treats autoimmune diseases and cancer by blocking folic acid metabolism."),
    "hydroxychloroquine": (["nausea", "headache", "dizziness", "diarrhea"], ["retinal toxicity (vision damage)", "heart rhythm changes"], "This drug modifies the immune system to treat lupus and rheumatoid arthritis."),
    "sulfasalazine": (["nausea", "headache", "stomach upset", "orange urine"], ["blood disorders", "liver damage", "severe allergic reaction"], "This drug treats rheumatoid arthritis and ulcerative colitis by reducing inflammation."),
    "leflunomide": (["diarrhea", "nausea", "headache", "hair loss", "rash"], ["liver damage", "lung disease", "birth defects"], "This drug treats rheumatoid arthritis by blocking pyrimidine synthesis to suppress the immune system."),
    "adalimumab": (["injection site reactions", "upper respiratory infections", "headache"], ["serious infections (TB)", "lymphoma risk", "heart failure worsening"], "This drug treats autoimmune diseases by blocking TNF-alpha inflammation."),
    "etanercept": (["injection site reactions", "headache", "upper respiratory infections"], ["serious infections", "lymphoma risk", "nerve damage"], "This drug treats autoimmune diseases by binding TNF-alpha to reduce inflammation."),
    "infliximab": (["infusion reactions", "headache", "stomach pain"], ["serious infections (TB)", "lymphoma risk", "liver damage"], "This drug treats autoimmune diseases by neutralizing TNF-alpha through IV infusion."),
    "tocilizumab": (["upper respiratory infections", "headache", "injection reactions"], ["serious infections", "liver damage", "GI perforation"], "This drug treats rheumatoid arthritis by blocking interleukin-6."),
    "baricitinib": (["upper respiratory infections", "nausea", "herpes reactivation"], ["serious infections", "blood clots", "cancer risk"], "This drug treats rheumatoid arthritis by blocking JAK enzymes to reduce inflammation."),
    "tofacitinib": (["upper respiratory infections", "headache", "diarrhea"], ["serious infections", "blood clots", "cancer risk"], "This drug treats rheumatoid arthritis by inhibiting JAK kinases."),
    "upadacitinib": (["upper respiratory infections", "nausea", "cough", "acne"], ["serious infections", "blood clots", "cancer risk"], "This drug treats autoimmune diseases by selectively inhibiting JAK1."),
    "ustekinumab": (["upper respiratory infections", "headache", "fatigue"], ["serious infections", "cancer risk"], "This drug treats psoriasis and Crohn's by blocking IL-12 and IL-23."),
    "secukinumab": (["upper respiratory infections", "diarrhea", "injection site reactions"], ["serious infections", "inflammatory bowel disease"], "This drug treats psoriasis and arthritis by blocking interleukin-17A."),
    "cyclosporine": (["tremor", "high blood pressure", "kidney problems", "excess hair growth"], ["kidney failure", "cancer risk", "serious infections"], "This drug suppresses the immune system by blocking T-cell activation to prevent organ rejection."),
    "tacrolimus": (["tremor", "headache", "high blood pressure", "kidney problems", "diabetes"], ["kidney failure", "cancer risk", "serious infections"], "This drug prevents organ rejection by blocking T-cell activation more potently than cyclosporine."),
    "mycophenolate": (["nausea", "diarrhea", "vomiting", "stomach pain"], ["severe infections", "blood cell suppression", "birth defects"], "This drug prevents organ rejection by blocking immune cell proliferation."),
    # ── Urology / Sexual Health ──────────────────────────────────────────────
    "tamsulosin": (["dizziness", "runny nose", "abnormal ejaculation", "headache"], ["severe low blood pressure", "floppy iris during eye surgery"], "This drug relaxes prostate and bladder muscles to improve urine flow."),
    "doxazosin": (["dizziness", "fatigue", "headache", "low blood pressure"], ["first-dose fainting", "priapism"], "This drug relaxes muscles in the prostate and blood vessels to improve urine flow and lower blood pressure."),
    "finasteride": (["decreased sex drive", "erectile dysfunction", "decreased semen"], ["breast cancer (rare)", "depression"], "This drug shrinks the prostate and grows hair by blocking conversion of testosterone to DHT."),
    "dutasteride": (["decreased sex drive", "erectile dysfunction", "breast tenderness"], ["breast cancer (rare)", "birth defects if handled by pregnant women"], "This drug blocks both types of 5-alpha reductase to shrink the prostate more effectively."),
    "sildenafil": (["headache", "flushing", "upset stomach", "nasal congestion", "vision changes"], ["sudden hearing loss", "priapism", "sudden vision loss"], "This drug treats erectile dysfunction by blocking PDE-5 to increase blood flow."),
    "tadalafil": (["headache", "muscle aches", "flushing", "nasal congestion", "back pain"], ["sudden hearing loss", "priapism", "sudden vision loss"], "This drug treats ED and enlarged prostate by blocking PDE-5 with a long 36-hour duration."),
    "oxybutynin": (["dry mouth", "constipation", "drowsiness", "blurred vision", "dizziness"], ["heat stroke risk", "urinary retention", "confusion in elderly"], "This drug treats overactive bladder by blocking acetylcholine receptors on bladder muscle."),
    "tolterodine": (["dry mouth", "headache", "constipation", "dizziness"], ["urinary retention", "QT prolongation"], "This drug treats overactive bladder with less dry mouth than oxybutynin."),
    "mirabegron": (["high blood pressure", "urinary tract infection", "headache", "runny nose"], ["urinary retention", "severe high blood pressure"], "This drug relaxes the bladder by activating beta-3 receptors to reduce urgency."),
    # ── Osteoporosis / Bone ──────────────────────────────────────────────────
    "alendronate": (["stomach pain", "heartburn", "nausea", "constipation"], ["esophageal ulcer", "jaw bone death (osteonecrosis)", "atypical femur fracture"], "This drug strengthens bones by blocking osteoclasts from breaking down bone tissue."),
    "risedronate": (["stomach upset", "heartburn", "headache", "joint pain"], ["esophageal ulcer", "jaw bone death", "atypical femur fracture"], "This drug prevents bone loss by inhibiting osteoclast bone resorption."),
    "ibandronate": (["stomach pain", "heartburn", "diarrhea"], ["jaw bone death", "atypical femur fracture", "esophageal ulcer"], "This drug prevents bone loss with monthly dosing by blocking osteoclast activity."),
    "denosumab": (["back pain", "joint pain", "muscle pain", "skin infections"], ["jaw bone death", "atypical femur fracture", "severe low calcium"], "This drug prevents bone loss by blocking RANKL to reduce osteoclast formation."),
    "raloxifene": (["hot flashes", "leg cramps", "swelling", "joint pain"], ["blood clots (DVT, PE)", "stroke"], "This drug prevents osteoporosis in postmenopausal women by mimicking estrogen's effects on bone."),
    "teriparatide": (["dizziness", "nausea", "leg cramps", "injection site pain"], ["osteosarcoma risk (in animals)", "high calcium"], "This drug builds new bone by mimicking parathyroid hormone to stimulate bone formation."),
    "romosozumab": (["joint pain", "headache", "injection site reactions"], ["heart attack risk", "stroke risk", "jaw bone death"], "This drug builds bone and reduces bone loss by blocking sclerostin."),
    # ── Vitamins / Minerals ──────────────────────────────────────────────────
    "folic acid": (["nausea", "bloating", "gas", "bitter taste"], ["allergic reaction (rare)", "may mask B12 deficiency"], "This vitamin supports DNA synthesis and red blood cell production."),
    "cholecalciferol": (["nausea", "constipation", "weakness"], ["high calcium with excessive doses", "kidney stones"], "This vitamin helps the body absorb calcium to maintain strong bones."),
    "ergocalciferol": (["nausea", "headache", "dry mouth", "metallic taste"], ["high calcium with excessive doses", "kidney damage"], "This plant-derived vitamin D helps the body absorb calcium."),
    "calcium carbonate": (["constipation", "gas", "bloating", "stomach upset"], ["kidney stones", "high calcium levels"], "This supplement provides calcium for bone health and neutralizes stomach acid."),
    "calcium citrate": (["nausea", "gas", "stomach upset"], ["kidney stones", "high calcium levels"], "This supplement provides easily absorbed calcium for people with low stomach acid."),
    "ferrous sulfate": (["constipation", "nausea", "stomach upset", "dark stools"], ["iron poisoning with overdose (especially in children)", "stomach ulcers"], "This supplement provides iron to treat iron deficiency anemia."),
    "potassium chloride": (["nausea", "vomiting", "diarrhea", "stomach upset"], ["dangerously high potassium", "GI ulceration"], "This supplement replaces potassium lost from diuretics or other conditions."),
    "magnesium oxide": (["diarrhea", "nausea", "stomach cramps"], ["high magnesium in kidney disease"], "This supplement provides magnesium for deficiency and acts as an antacid."),
    # ── Ophthalmology ────────────────────────────────────────────────────────
    "latanoprost": (["eye redness", "eyelash growth", "eye color darkening", "stinging"], ["macular edema", "eye inflammation"], "This drug lowers eye pressure by increasing fluid drainage from the eye."),
    "timolol": (["eye stinging", "blurred vision", "headache"], ["bronchospasm", "slow heartbeat", "depression"], "This drug lowers eye pressure by reducing fluid production in the eye."),
    "brimonidine": (["eye redness", "dry mouth", "drowsiness", "blurred vision"], ["severe low blood pressure in children", "severe allergic reaction"], "This drug lowers eye pressure by reducing fluid production and increasing drainage."),
    "dorzolamide": (["eye stinging", "bitter taste", "blurred vision"], ["severe allergic reaction", "blood disorders"], "This drug lowers eye pressure by blocking carbonic anhydrase to reduce fluid production."),
    # ── Oncology (common orals) ──────────────────────────────────────────────
    "tamoxifen": (["hot flashes", "nausea", "leg cramps", "vaginal discharge"], ["endometrial cancer", "blood clots", "stroke"], "This drug treats and prevents breast cancer by blocking estrogen receptors."),
    "anastrozole": (["joint pain", "hot flashes", "weakness", "mood changes"], ["bone fractures", "cardiovascular events"], "This drug treats breast cancer by blocking the enzyme that makes estrogen."),
    "letrozole": (["hot flashes", "joint pain", "fatigue", "sweating"], ["bone fractures", "cardiovascular events"], "This drug treats breast cancer by blocking aromatase to reduce estrogen levels."),
    "imatinib": (["nausea", "muscle cramps", "diarrhea", "rash", "fatigue"], ["liver damage", "heart failure", "severe fluid retention"], "This drug treats certain cancers by blocking the abnormal tyrosine kinase protein."),
    "ibrutinib": (["diarrhea", "bruising", "fatigue", "muscle pain"], ["serious bleeding", "atrial fibrillation", "severe infections"], "This drug treats blood cancers by blocking Bruton's tyrosine kinase."),
    # ── HIV / Antiretrovirals ────────────────────────────────────────────────
    "emtricitabine-tenofovir": (["nausea", "headache", "diarrhea", "fatigue"], ["kidney damage", "bone density loss", "lactic acidosis"], "This drug combination prevents HIV replication by blocking reverse transcriptase."),
    "bictegravir-emtricitabine-tenofovir": (["headache", "nausea", "diarrhea"], ["kidney damage", "lactic acidosis"], "This drug treats HIV using three medications that block viral replication at multiple steps."),
    "dolutegravir": (["insomnia", "headache", "nausea"], ["liver damage", "immune reconstitution syndrome"], "This drug treats HIV by blocking integrase to prevent the virus from inserting DNA into cells."),
    "ritonavir": (["nausea", "diarrhea", "vomiting", "taste changes"], ["liver damage", "pancreatitis", "heart rhythm changes"], "This drug boosts other HIV medications by blocking the enzyme that breaks them down."),
    # ── Dermatology ──────────────────────────────────────────────────────────
    "tretinoin": (["skin redness", "peeling", "dryness", "sun sensitivity", "stinging"], ["severe sunburn", "birth defects if taken orally"], "This drug treats acne by speeding up skin cell turnover to unclog pores."),
    "isotretinoin": (["dry lips", "dry skin", "dry eyes", "nosebleeds", "joint pain"], ["birth defects (iPLEDGE required)", "depression", "liver damage", "inflammatory bowel disease"], "This drug treats severe acne by shrinking oil glands and reducing skin oil production."),
    "clobetasol": (["skin thinning", "burning", "stinging", "stretch marks"], ["adrenal suppression", "skin atrophy with prolonged use"], "This drug is an ultra-potent topical steroid that treats severe skin inflammation."),
    "hydrocortisone": (["skin thinning", "burning", "itching"], ["adrenal suppression with large amounts", "skin infections"], "This drug is a mild topical steroid that treats minor skin inflammation and itching."),
    # ── Migraine ─────────────────────────────────────────────────────────────
    "sumatriptan": (["tingling", "flushing", "chest tightness", "drowsiness"], ["heart attack", "stroke", "serotonin syndrome"], "This drug treats migraines by narrowing blood vessels and blocking pain pathways in the brain."),
    "rizatriptan": (["dizziness", "drowsiness", "fatigue", "chest tightness"], ["heart attack", "stroke"], "This drug treats migraines by activating serotonin receptors to narrow blood vessels."),
    "ubrogepant": (["nausea", "drowsiness", "dry mouth"], ["liver problems"], "This drug treats migraines by blocking CGRP receptors to reduce pain and inflammation."),
    "rimegepant": (["nausea", "stomach pain"], ["severe allergic reaction"], "This drug treats and prevents migraines by blocking CGRP receptors."),
    "erenumab": (["injection site reactions", "constipation", "muscle cramps"], ["severe constipation", "high blood pressure"], "This drug prevents migraines by blocking the CGRP receptor with monthly injections."),
    "fremanezumab": (["injection site reactions", "rash"], ["severe allergic reaction"], "This drug prevents migraines by neutralizing CGRP protein with monthly or quarterly injections."),
    # ── Sleep / OTC Misc ─────────────────────────────────────────────────────
    "melatonin": (["drowsiness", "headache", "dizziness", "nausea"], ["daytime grogginess", "hormone effects in children"], "This supplement helps regulate the sleep-wake cycle by mimicking the body's natural sleep hormone."),
    "doxylamine": (["drowsiness", "dry mouth", "dizziness", "constipation"], ["urinary retention", "confusion in elderly"], "This drug causes drowsiness by blocking histamine receptors to aid sleep."),
    "zinc": (["nausea", "metallic taste", "stomach upset"], ["copper deficiency with chronic use"], "This mineral supports immune function and wound healing."),
    "vitamin c": (["nausea", "stomach cramps", "diarrhea (at high doses)"], ["kidney stones with excessive doses"], "This vitamin supports immune function and acts as an antioxidant."),
}

import re, sys, pathlib

catalog_path = pathlib.Path(__file__).parent / "drug_catalog.py"
src = catalog_path.read_text(encoding="utf-8")

count = 0
for drug_name, (common, serious, mechanism) in DRUG_DATA.items():
    # Find the 4-tuple pattern for this drug  
    # We look for the drug in quotes followed by a bracket
    escaped = re.escape(drug_name)
    pattern = rf'(\("{escaped}",\s*\[.*?\],\s*".*?",\s*)(True|False)\)'
    match = re.search(pattern, src, re.DOTALL)
    if match:
        old = match.group(0)
        prefix = match.group(1)
        hr = match.group(2)
        common_str = repr(common)
        serious_str = repr(serious)
        mech_str = repr(mechanism)
        new = f'{prefix}{hr},\n     {common_str},\n     {serious_str},\n     {mech_str})'
        src = src.replace(old, new, 1)
        count += 1

catalog_path.write_text(src, encoding="utf-8")
print(f"Updated {count} drugs")
